// Code generated by ent, DO NOT EDIT.

package linkcardledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the linkcardledger type in the database.
	Label = "link_card_ledger"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOperationID holds the string denoting the operation_id field in the database.
	FieldOperationID = "operation_id"
	// FieldAPIKeyID holds the string denoting the api_key_id field in the database.
	FieldAPIKeyID = "api_key_id"
	// FieldCreatorUserID holds the string denoting the creator_user_id field in the database.
	FieldCreatorUserID = "creator_user_id"
	// FieldEntryType holds the string denoting the entry_type field in the database.
	FieldEntryType = "entry_type"
	// FieldReserveDelta holds the string denoting the reserve_delta field in the database.
	FieldReserveDelta = "reserve_delta"
	// FieldCreatorBalanceDelta holds the string denoting the creator_balance_delta field in the database.
	FieldCreatorBalanceDelta = "creator_balance_delta"
	// FieldQuotaBefore holds the string denoting the quota_before field in the database.
	FieldQuotaBefore = "quota_before"
	// FieldQuotaAfter holds the string denoting the quota_after field in the database.
	FieldQuotaAfter = "quota_after"
	// FieldQuotaUsedBefore holds the string denoting the quota_used_before field in the database.
	FieldQuotaUsedBefore = "quota_used_before"
	// FieldQuotaUsedAfter holds the string denoting the quota_used_after field in the database.
	FieldQuotaUsedAfter = "quota_used_after"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldActorUserID holds the string denoting the actor_user_id field in the database.
	FieldActorUserID = "actor_user_id"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldMetadata holds the string denoting the metadata field in the database.
	FieldMetadata = "metadata"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the linkcardledger in the database.
	Table = "link_card_ledger"
)

// Columns holds all SQL columns for linkcardledger fields.
var Columns = []string{
	FieldID,
	FieldOperationID,
	FieldAPIKeyID,
	FieldCreatorUserID,
	FieldEntryType,
	FieldReserveDelta,
	FieldCreatorBalanceDelta,
	FieldQuotaBefore,
	FieldQuotaAfter,
	FieldQuotaUsedBefore,
	FieldQuotaUsedAfter,
	FieldRequestID,
	FieldActorUserID,
	FieldReason,
	FieldMetadata,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// EntryTypeValidator is a validator for the "entry_type" field. It is called by the builders before save.
	EntryTypeValidator func(string) error
	// DefaultCreatorBalanceDelta holds the default value on creation for the "creator_balance_delta" field.
	DefaultCreatorBalanceDelta float64
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// DefaultReason holds the default value on creation for the "reason" field.
	DefaultReason string
	// ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	ReasonValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the LinkCardLedger queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOperationID orders the results by the operation_id field.
func ByOperationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOperationID, opts...).ToFunc()
}

// ByAPIKeyID orders the results by the api_key_id field.
func ByAPIKeyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAPIKeyID, opts...).ToFunc()
}

// ByCreatorUserID orders the results by the creator_user_id field.
func ByCreatorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatorUserID, opts...).ToFunc()
}

// ByEntryType orders the results by the entry_type field.
func ByEntryType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEntryType, opts...).ToFunc()
}

// ByReserveDelta orders the results by the reserve_delta field.
func ByReserveDelta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReserveDelta, opts...).ToFunc()
}

// ByCreatorBalanceDelta orders the results by the creator_balance_delta field.
func ByCreatorBalanceDelta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatorBalanceDelta, opts...).ToFunc()
}

// ByQuotaBefore orders the results by the quota_before field.
func ByQuotaBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaBefore, opts...).ToFunc()
}

// ByQuotaAfter orders the results by the quota_after field.
func ByQuotaAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaAfter, opts...).ToFunc()
}

// ByQuotaUsedBefore orders the results by the quota_used_before field.
func ByQuotaUsedBefore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaUsedBefore, opts...).ToFunc()
}

// ByQuotaUsedAfter orders the results by the quota_used_after field.
func ByQuotaUsedAfter(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaUsedAfter, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByActorUserID orders the results by the actor_user_id field.
func ByActorUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActorUserID, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
