// Code generated by ent, DO NOT EDIT.

package linkcardledger

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldID, id))
}

// OperationID applies equality check predicate on the "operation_id" field. It's identical to OperationIDEQ.
func OperationID(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldOperationID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldAPIKeyID, v))
}

// CreatorUserID applies equality check predicate on the "creator_user_id" field. It's identical to CreatorUserIDEQ.
func CreatorUserID(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldCreatorUserID, v))
}

// EntryType applies equality check predicate on the "entry_type" field. It's identical to EntryTypeEQ.
func EntryType(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldEntryType, v))
}

// ReserveDelta applies equality check predicate on the "reserve_delta" field. It's identical to ReserveDeltaEQ.
func ReserveDelta(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldReserveDelta, v))
}

// CreatorBalanceDelta applies equality check predicate on the "creator_balance_delta" field. It's identical to CreatorBalanceDeltaEQ.
func CreatorBalanceDelta(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldCreatorBalanceDelta, v))
}

// QuotaBefore applies equality check predicate on the "quota_before" field. It's identical to QuotaBeforeEQ.
func QuotaBefore(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldQuotaBefore, v))
}

// QuotaAfter applies equality check predicate on the "quota_after" field. It's identical to QuotaAfterEQ.
func QuotaAfter(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldQuotaAfter, v))
}

// QuotaUsedBefore applies equality check predicate on the "quota_used_before" field. It's identical to QuotaUsedBeforeEQ.
func QuotaUsedBefore(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldQuotaUsedBefore, v))
}

// QuotaUsedAfter applies equality check predicate on the "quota_used_after" field. It's identical to QuotaUsedAfterEQ.
func QuotaUsedAfter(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldQuotaUsedAfter, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldRequestID, v))
}

// ActorUserID applies equality check predicate on the "actor_user_id" field. It's identical to ActorUserIDEQ.
func ActorUserID(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldActorUserID, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldReason, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// OperationIDEQ applies the EQ predicate on the "operation_id" field.
func OperationIDEQ(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldOperationID, v))
}

// OperationIDNEQ applies the NEQ predicate on the "operation_id" field.
func OperationIDNEQ(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldOperationID, v))
}

// OperationIDIn applies the In predicate on the "operation_id" field.
func OperationIDIn(vs ...int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldOperationID, vs...))
}

// OperationIDNotIn applies the NotIn predicate on the "operation_id" field.
func OperationIDNotIn(vs ...int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldOperationID, vs...))
}

// OperationIDGT applies the GT predicate on the "operation_id" field.
func OperationIDGT(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldOperationID, v))
}

// OperationIDGTE applies the GTE predicate on the "operation_id" field.
func OperationIDGTE(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldOperationID, v))
}

// OperationIDLT applies the LT predicate on the "operation_id" field.
func OperationIDLT(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldOperationID, v))
}

// OperationIDLTE applies the LTE predicate on the "operation_id" field.
func OperationIDLTE(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldOperationID, v))
}

// OperationIDIsNil applies the IsNil predicate on the "operation_id" field.
func OperationIDIsNil() predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIsNull(FieldOperationID))
}

// OperationIDNotNil applies the NotNil predicate on the "operation_id" field.
func OperationIDNotNil() predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotNull(FieldOperationID))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldAPIKeyID, v))
}

// CreatorUserIDEQ applies the EQ predicate on the "creator_user_id" field.
func CreatorUserIDEQ(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldCreatorUserID, v))
}

// CreatorUserIDNEQ applies the NEQ predicate on the "creator_user_id" field.
func CreatorUserIDNEQ(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldCreatorUserID, v))
}

// CreatorUserIDIn applies the In predicate on the "creator_user_id" field.
func CreatorUserIDIn(vs ...int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldCreatorUserID, vs...))
}

// CreatorUserIDNotIn applies the NotIn predicate on the "creator_user_id" field.
func CreatorUserIDNotIn(vs ...int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldCreatorUserID, vs...))
}

// CreatorUserIDGT applies the GT predicate on the "creator_user_id" field.
func CreatorUserIDGT(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldCreatorUserID, v))
}

// CreatorUserIDGTE applies the GTE predicate on the "creator_user_id" field.
func CreatorUserIDGTE(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldCreatorUserID, v))
}

// CreatorUserIDLT applies the LT predicate on the "creator_user_id" field.
func CreatorUserIDLT(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldCreatorUserID, v))
}

// CreatorUserIDLTE applies the LTE predicate on the "creator_user_id" field.
func CreatorUserIDLTE(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldCreatorUserID, v))
}

// EntryTypeEQ applies the EQ predicate on the "entry_type" field.
func EntryTypeEQ(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldEntryType, v))
}

// EntryTypeNEQ applies the NEQ predicate on the "entry_type" field.
func EntryTypeNEQ(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldEntryType, v))
}

// EntryTypeIn applies the In predicate on the "entry_type" field.
func EntryTypeIn(vs ...string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldEntryType, vs...))
}

// EntryTypeNotIn applies the NotIn predicate on the "entry_type" field.
func EntryTypeNotIn(vs ...string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldEntryType, vs...))
}

// EntryTypeGT applies the GT predicate on the "entry_type" field.
func EntryTypeGT(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldEntryType, v))
}

// EntryTypeGTE applies the GTE predicate on the "entry_type" field.
func EntryTypeGTE(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldEntryType, v))
}

// EntryTypeLT applies the LT predicate on the "entry_type" field.
func EntryTypeLT(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldEntryType, v))
}

// EntryTypeLTE applies the LTE predicate on the "entry_type" field.
func EntryTypeLTE(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldEntryType, v))
}

// EntryTypeContains applies the Contains predicate on the "entry_type" field.
func EntryTypeContains(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldContains(FieldEntryType, v))
}

// EntryTypeHasPrefix applies the HasPrefix predicate on the "entry_type" field.
func EntryTypeHasPrefix(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldHasPrefix(FieldEntryType, v))
}

// EntryTypeHasSuffix applies the HasSuffix predicate on the "entry_type" field.
func EntryTypeHasSuffix(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldHasSuffix(FieldEntryType, v))
}

// EntryTypeEqualFold applies the EqualFold predicate on the "entry_type" field.
func EntryTypeEqualFold(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEqualFold(FieldEntryType, v))
}

// EntryTypeContainsFold applies the ContainsFold predicate on the "entry_type" field.
func EntryTypeContainsFold(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldContainsFold(FieldEntryType, v))
}

// ReserveDeltaEQ applies the EQ predicate on the "reserve_delta" field.
func ReserveDeltaEQ(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldReserveDelta, v))
}

// ReserveDeltaNEQ applies the NEQ predicate on the "reserve_delta" field.
func ReserveDeltaNEQ(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldReserveDelta, v))
}

// ReserveDeltaIn applies the In predicate on the "reserve_delta" field.
func ReserveDeltaIn(vs ...float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldReserveDelta, vs...))
}

// ReserveDeltaNotIn applies the NotIn predicate on the "reserve_delta" field.
func ReserveDeltaNotIn(vs ...float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldReserveDelta, vs...))
}

// ReserveDeltaGT applies the GT predicate on the "reserve_delta" field.
func ReserveDeltaGT(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldReserveDelta, v))
}

// ReserveDeltaGTE applies the GTE predicate on the "reserve_delta" field.
func ReserveDeltaGTE(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldReserveDelta, v))
}

// ReserveDeltaLT applies the LT predicate on the "reserve_delta" field.
func ReserveDeltaLT(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldReserveDelta, v))
}

// ReserveDeltaLTE applies the LTE predicate on the "reserve_delta" field.
func ReserveDeltaLTE(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldReserveDelta, v))
}

// CreatorBalanceDeltaEQ applies the EQ predicate on the "creator_balance_delta" field.
func CreatorBalanceDeltaEQ(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldCreatorBalanceDelta, v))
}

// CreatorBalanceDeltaNEQ applies the NEQ predicate on the "creator_balance_delta" field.
func CreatorBalanceDeltaNEQ(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldCreatorBalanceDelta, v))
}

// CreatorBalanceDeltaIn applies the In predicate on the "creator_balance_delta" field.
func CreatorBalanceDeltaIn(vs ...float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldCreatorBalanceDelta, vs...))
}

// CreatorBalanceDeltaNotIn applies the NotIn predicate on the "creator_balance_delta" field.
func CreatorBalanceDeltaNotIn(vs ...float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldCreatorBalanceDelta, vs...))
}

// CreatorBalanceDeltaGT applies the GT predicate on the "creator_balance_delta" field.
func CreatorBalanceDeltaGT(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldCreatorBalanceDelta, v))
}

// CreatorBalanceDeltaGTE applies the GTE predicate on the "creator_balance_delta" field.
func CreatorBalanceDeltaGTE(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldCreatorBalanceDelta, v))
}

// CreatorBalanceDeltaLT applies the LT predicate on the "creator_balance_delta" field.
func CreatorBalanceDeltaLT(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldCreatorBalanceDelta, v))
}

// CreatorBalanceDeltaLTE applies the LTE predicate on the "creator_balance_delta" field.
func CreatorBalanceDeltaLTE(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldCreatorBalanceDelta, v))
}

// QuotaBeforeEQ applies the EQ predicate on the "quota_before" field.
func QuotaBeforeEQ(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldQuotaBefore, v))
}

// QuotaBeforeNEQ applies the NEQ predicate on the "quota_before" field.
func QuotaBeforeNEQ(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldQuotaBefore, v))
}

// QuotaBeforeIn applies the In predicate on the "quota_before" field.
func QuotaBeforeIn(vs ...float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldQuotaBefore, vs...))
}

// QuotaBeforeNotIn applies the NotIn predicate on the "quota_before" field.
func QuotaBeforeNotIn(vs ...float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldQuotaBefore, vs...))
}

// QuotaBeforeGT applies the GT predicate on the "quota_before" field.
func QuotaBeforeGT(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldQuotaBefore, v))
}

// QuotaBeforeGTE applies the GTE predicate on the "quota_before" field.
func QuotaBeforeGTE(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldQuotaBefore, v))
}

// QuotaBeforeLT applies the LT predicate on the "quota_before" field.
func QuotaBeforeLT(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldQuotaBefore, v))
}

// QuotaBeforeLTE applies the LTE predicate on the "quota_before" field.
func QuotaBeforeLTE(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldQuotaBefore, v))
}

// QuotaAfterEQ applies the EQ predicate on the "quota_after" field.
func QuotaAfterEQ(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldQuotaAfter, v))
}

// QuotaAfterNEQ applies the NEQ predicate on the "quota_after" field.
func QuotaAfterNEQ(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldQuotaAfter, v))
}

// QuotaAfterIn applies the In predicate on the "quota_after" field.
func QuotaAfterIn(vs ...float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldQuotaAfter, vs...))
}

// QuotaAfterNotIn applies the NotIn predicate on the "quota_after" field.
func QuotaAfterNotIn(vs ...float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldQuotaAfter, vs...))
}

// QuotaAfterGT applies the GT predicate on the "quota_after" field.
func QuotaAfterGT(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldQuotaAfter, v))
}

// QuotaAfterGTE applies the GTE predicate on the "quota_after" field.
func QuotaAfterGTE(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldQuotaAfter, v))
}

// QuotaAfterLT applies the LT predicate on the "quota_after" field.
func QuotaAfterLT(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldQuotaAfter, v))
}

// QuotaAfterLTE applies the LTE predicate on the "quota_after" field.
func QuotaAfterLTE(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldQuotaAfter, v))
}

// QuotaUsedBeforeEQ applies the EQ predicate on the "quota_used_before" field.
func QuotaUsedBeforeEQ(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldQuotaUsedBefore, v))
}

// QuotaUsedBeforeNEQ applies the NEQ predicate on the "quota_used_before" field.
func QuotaUsedBeforeNEQ(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldQuotaUsedBefore, v))
}

// QuotaUsedBeforeIn applies the In predicate on the "quota_used_before" field.
func QuotaUsedBeforeIn(vs ...float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldQuotaUsedBefore, vs...))
}

// QuotaUsedBeforeNotIn applies the NotIn predicate on the "quota_used_before" field.
func QuotaUsedBeforeNotIn(vs ...float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldQuotaUsedBefore, vs...))
}

// QuotaUsedBeforeGT applies the GT predicate on the "quota_used_before" field.
func QuotaUsedBeforeGT(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldQuotaUsedBefore, v))
}

// QuotaUsedBeforeGTE applies the GTE predicate on the "quota_used_before" field.
func QuotaUsedBeforeGTE(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldQuotaUsedBefore, v))
}

// QuotaUsedBeforeLT applies the LT predicate on the "quota_used_before" field.
func QuotaUsedBeforeLT(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldQuotaUsedBefore, v))
}

// QuotaUsedBeforeLTE applies the LTE predicate on the "quota_used_before" field.
func QuotaUsedBeforeLTE(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldQuotaUsedBefore, v))
}

// QuotaUsedAfterEQ applies the EQ predicate on the "quota_used_after" field.
func QuotaUsedAfterEQ(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldQuotaUsedAfter, v))
}

// QuotaUsedAfterNEQ applies the NEQ predicate on the "quota_used_after" field.
func QuotaUsedAfterNEQ(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldQuotaUsedAfter, v))
}

// QuotaUsedAfterIn applies the In predicate on the "quota_used_after" field.
func QuotaUsedAfterIn(vs ...float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldQuotaUsedAfter, vs...))
}

// QuotaUsedAfterNotIn applies the NotIn predicate on the "quota_used_after" field.
func QuotaUsedAfterNotIn(vs ...float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldQuotaUsedAfter, vs...))
}

// QuotaUsedAfterGT applies the GT predicate on the "quota_used_after" field.
func QuotaUsedAfterGT(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldQuotaUsedAfter, v))
}

// QuotaUsedAfterGTE applies the GTE predicate on the "quota_used_after" field.
func QuotaUsedAfterGTE(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldQuotaUsedAfter, v))
}

// QuotaUsedAfterLT applies the LT predicate on the "quota_used_after" field.
func QuotaUsedAfterLT(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldQuotaUsedAfter, v))
}

// QuotaUsedAfterLTE applies the LTE predicate on the "quota_used_after" field.
func QuotaUsedAfterLTE(v float64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldQuotaUsedAfter, v))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldContainsFold(FieldRequestID, v))
}

// ActorUserIDEQ applies the EQ predicate on the "actor_user_id" field.
func ActorUserIDEQ(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldActorUserID, v))
}

// ActorUserIDNEQ applies the NEQ predicate on the "actor_user_id" field.
func ActorUserIDNEQ(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldActorUserID, v))
}

// ActorUserIDIn applies the In predicate on the "actor_user_id" field.
func ActorUserIDIn(vs ...int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldActorUserID, vs...))
}

// ActorUserIDNotIn applies the NotIn predicate on the "actor_user_id" field.
func ActorUserIDNotIn(vs ...int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldActorUserID, vs...))
}

// ActorUserIDGT applies the GT predicate on the "actor_user_id" field.
func ActorUserIDGT(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldActorUserID, v))
}

// ActorUserIDGTE applies the GTE predicate on the "actor_user_id" field.
func ActorUserIDGTE(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldActorUserID, v))
}

// ActorUserIDLT applies the LT predicate on the "actor_user_id" field.
func ActorUserIDLT(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldActorUserID, v))
}

// ActorUserIDLTE applies the LTE predicate on the "actor_user_id" field.
func ActorUserIDLTE(v int64) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldActorUserID, v))
}

// ActorUserIDIsNil applies the IsNil predicate on the "actor_user_id" field.
func ActorUserIDIsNil() predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIsNull(FieldActorUserID))
}

// ActorUserIDNotNil applies the NotNil predicate on the "actor_user_id" field.
func ActorUserIDNotNil() predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotNull(FieldActorUserID))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldContainsFold(FieldReason, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotNull(FieldMetadata))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LinkCardLedger) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LinkCardLedger) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LinkCardLedger) predicate.LinkCardLedger {
	return predicate.LinkCardLedger(sql.NotPredicates(p))
}
