// Code generated by ent, DO NOT EDIT.

package linkcardgroupauthorization

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldLTE(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldEQ(FieldGroupID, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldEQ(FieldEnabled, v))
}

// SortOrder applies equality check predicate on the "sort_order" field. It's identical to SortOrderEQ.
func SortOrder(v int) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldEQ(FieldSortOrder, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldLTE(FieldGroupID, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldNEQ(FieldEnabled, v))
}

// SortOrderEQ applies the EQ predicate on the "sort_order" field.
func SortOrderEQ(v int) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldEQ(FieldSortOrder, v))
}

// SortOrderNEQ applies the NEQ predicate on the "sort_order" field.
func SortOrderNEQ(v int) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldNEQ(FieldSortOrder, v))
}

// SortOrderIn applies the In predicate on the "sort_order" field.
func SortOrderIn(vs ...int) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldIn(FieldSortOrder, vs...))
}

// SortOrderNotIn applies the NotIn predicate on the "sort_order" field.
func SortOrderNotIn(vs ...int) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldNotIn(FieldSortOrder, vs...))
}

// SortOrderGT applies the GT predicate on the "sort_order" field.
func SortOrderGT(v int) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldGT(FieldSortOrder, v))
}

// SortOrderGTE applies the GTE predicate on the "sort_order" field.
func SortOrderGTE(v int) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldGTE(FieldSortOrder, v))
}

// SortOrderLT applies the LT predicate on the "sort_order" field.
func SortOrderLT(v int) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldLT(FieldSortOrder, v))
}

// SortOrderLTE applies the LTE predicate on the "sort_order" field.
func SortOrderLTE(v int) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldLTE(FieldSortOrder, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LinkCardGroupAuthorization) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LinkCardGroupAuthorization) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LinkCardGroupAuthorization) predicate.LinkCardGroupAuthorization {
	return predicate.LinkCardGroupAuthorization(sql.NotPredicates(p))
}
