// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/linkcardoperation"
)

// LinkCardOperationCreate is the builder for creating a LinkCardOperation entity.
type LinkCardOperationCreate struct {
	config
	mutation *LinkCardOperationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetScope sets the "scope" field.
func (_c *LinkCardOperationCreate) SetScope(v string) *LinkCardOperationCreate {
	_c.mutation.SetScope(v)
	return _c
}

// SetActorUserID sets the "actor_user_id" field.
func (_c *LinkCardOperationCreate) SetActorUserID(v int64) *LinkCardOperationCreate {
	_c.mutation.SetActorUserID(v)
	return _c
}

// SetCreatorUserID sets the "creator_user_id" field.
func (_c *LinkCardOperationCreate) SetCreatorUserID(v int64) *LinkCardOperationCreate {
	_c.mutation.SetCreatorUserID(v)
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *LinkCardOperationCreate) SetAPIKeyID(v int64) *LinkCardOperationCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_c *LinkCardOperationCreate) SetNillableAPIKeyID(v *int64) *LinkCardOperationCreate {
	if v != nil {
		_c.SetAPIKeyID(*v)
	}
	return _c
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (_c *LinkCardOperationCreate) SetIdempotencyKeyHash(v string) *LinkCardOperationCreate {
	_c.mutation.SetIdempotencyKeyHash(v)
	return _c
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (_c *LinkCardOperationCreate) SetRequestFingerprint(v string) *LinkCardOperationCreate {
	_c.mutation.SetRequestFingerprint(v)
	return _c
}

// SetResponseBody sets the "response_body" field.
func (_c *LinkCardOperationCreate) SetResponseBody(v map[string]interface{}) *LinkCardOperationCreate {
	_c.mutation.SetResponseBody(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LinkCardOperationCreate) SetCreatedAt(v time.Time) *LinkCardOperationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LinkCardOperationCreate) SetNillableCreatedAt(v *time.Time) *LinkCardOperationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the LinkCardOperationMutation object of the builder.
func (_c *LinkCardOperationCreate) Mutation() *LinkCardOperationMutation {
	return _c.mutation
}

// Save creates the LinkCardOperation in the database.
func (_c *LinkCardOperationCreate) Save(ctx context.Context) (*LinkCardOperation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LinkCardOperationCreate) SaveX(ctx context.Context) *LinkCardOperation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCardOperationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCardOperationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LinkCardOperationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := linkcardoperation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LinkCardOperationCreate) check() error {
	if _, ok := _c.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "LinkCardOperation.scope"`)}
	}
	if v, ok := _c.mutation.Scope(); ok {
		if err := linkcardoperation.ScopeValidator(v); err != nil {
			return &ValidationError{Name: "scope", err: fmt.Errorf(`ent: validator failed for field "LinkCardOperation.scope": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ActorUserID(); !ok {
		return &ValidationError{Name: "actor_user_id", err: errors.New(`ent: missing required field "LinkCardOperation.actor_user_id"`)}
	}
	if _, ok := _c.mutation.CreatorUserID(); !ok {
		return &ValidationError{Name: "creator_user_id", err: errors.New(`ent: missing required field "LinkCardOperation.creator_user_id"`)}
	}
	if _, ok := _c.mutation.IdempotencyKeyHash(); !ok {
		return &ValidationError{Name: "idempotency_key_hash", err: errors.New(`ent: missing required field "LinkCardOperation.idempotency_key_hash"`)}
	}
	if v, ok := _c.mutation.IdempotencyKeyHash(); ok {
		if err := linkcardoperation.IdempotencyKeyHashValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key_hash", err: fmt.Errorf(`ent: validator failed for field "LinkCardOperation.idempotency_key_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RequestFingerprint(); !ok {
		return &ValidationError{Name: "request_fingerprint", err: errors.New(`ent: missing required field "LinkCardOperation.request_fingerprint"`)}
	}
	if v, ok := _c.mutation.RequestFingerprint(); ok {
		if err := linkcardoperation.RequestFingerprintValidator(v); err != nil {
			return &ValidationError{Name: "request_fingerprint", err: fmt.Errorf(`ent: validator failed for field "LinkCardOperation.request_fingerprint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LinkCardOperation.created_at"`)}
	}
	return nil
}

func (_c *LinkCardOperationCreate) sqlSave(ctx context.Context) (*LinkCardOperation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LinkCardOperationCreate) createSpec() (*LinkCardOperation, *sqlgraph.CreateSpec) {
	var (
		_node = &LinkCardOperation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(linkcardoperation.Table, sqlgraph.NewFieldSpec(linkcardoperation.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Scope(); ok {
		_spec.SetField(linkcardoperation.FieldScope, field.TypeString, value)
		_node.Scope = value
	}
	if value, ok := _c.mutation.ActorUserID(); ok {
		_spec.SetField(linkcardoperation.FieldActorUserID, field.TypeInt64, value)
		_node.ActorUserID = value
	}
	if value, ok := _c.mutation.CreatorUserID(); ok {
		_spec.SetField(linkcardoperation.FieldCreatorUserID, field.TypeInt64, value)
		_node.CreatorUserID = value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(linkcardoperation.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = &value
	}
	if value, ok := _c.mutation.IdempotencyKeyHash(); ok {
		_spec.SetField(linkcardoperation.FieldIdempotencyKeyHash, field.TypeString, value)
		_node.IdempotencyKeyHash = value
	}
	if value, ok := _c.mutation.RequestFingerprint(); ok {
		_spec.SetField(linkcardoperation.FieldRequestFingerprint, field.TypeString, value)
		_node.RequestFingerprint = value
	}
	if value, ok := _c.mutation.ResponseBody(); ok {
		_spec.SetField(linkcardoperation.FieldResponseBody, field.TypeJSON, value)
		_node.ResponseBody = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(linkcardoperation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LinkCardOperation.Create().
//		SetScope(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LinkCardOperationUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (_c *LinkCardOperationCreate) OnConflict(opts ...sql.ConflictOption) *LinkCardOperationUpsertOne {
	_c.conflict = opts
	return &LinkCardOperationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LinkCardOperation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LinkCardOperationCreate) OnConflictColumns(columns ...string) *LinkCardOperationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LinkCardOperationUpsertOne{
		create: _c,
	}
}

type (
	// LinkCardOperationUpsertOne is the builder for "upsert"-ing
	//  one LinkCardOperation node.
	LinkCardOperationUpsertOne struct {
		create *LinkCardOperationCreate
	}

	// LinkCardOperationUpsert is the "OnConflict" setter.
	LinkCardOperationUpsert struct {
		*sql.UpdateSet
	}
)

// SetScope sets the "scope" field.
func (u *LinkCardOperationUpsert) SetScope(v string) *LinkCardOperationUpsert {
	u.Set(linkcardoperation.FieldScope, v)
	return u
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *LinkCardOperationUpsert) UpdateScope() *LinkCardOperationUpsert {
	u.SetExcluded(linkcardoperation.FieldScope)
	return u
}

// SetActorUserID sets the "actor_user_id" field.
func (u *LinkCardOperationUpsert) SetActorUserID(v int64) *LinkCardOperationUpsert {
	u.Set(linkcardoperation.FieldActorUserID, v)
	return u
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *LinkCardOperationUpsert) UpdateActorUserID() *LinkCardOperationUpsert {
	u.SetExcluded(linkcardoperation.FieldActorUserID)
	return u
}

// AddActorUserID adds v to the "actor_user_id" field.
func (u *LinkCardOperationUpsert) AddActorUserID(v int64) *LinkCardOperationUpsert {
	u.Add(linkcardoperation.FieldActorUserID, v)
	return u
}

// SetCreatorUserID sets the "creator_user_id" field.
func (u *LinkCardOperationUpsert) SetCreatorUserID(v int64) *LinkCardOperationUpsert {
	u.Set(linkcardoperation.FieldCreatorUserID, v)
	return u
}

// UpdateCreatorUserID sets the "creator_user_id" field to the value that was provided on create.
func (u *LinkCardOperationUpsert) UpdateCreatorUserID() *LinkCardOperationUpsert {
	u.SetExcluded(linkcardoperation.FieldCreatorUserID)
	return u
}

// AddCreatorUserID adds v to the "creator_user_id" field.
func (u *LinkCardOperationUpsert) AddCreatorUserID(v int64) *LinkCardOperationUpsert {
	u.Add(linkcardoperation.FieldCreatorUserID, v)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *LinkCardOperationUpsert) SetAPIKeyID(v int64) *LinkCardOperationUpsert {
	u.Set(linkcardoperation.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *LinkCardOperationUpsert) UpdateAPIKeyID() *LinkCardOperationUpsert {
	u.SetExcluded(linkcardoperation.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *LinkCardOperationUpsert) AddAPIKeyID(v int64) *LinkCardOperationUpsert {
	u.Add(linkcardoperation.FieldAPIKeyID, v)
	return u
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *LinkCardOperationUpsert) ClearAPIKeyID() *LinkCardOperationUpsert {
	u.SetNull(linkcardoperation.FieldAPIKeyID)
	return u
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (u *LinkCardOperationUpsert) SetIdempotencyKeyHash(v string) *LinkCardOperationUpsert {
	u.Set(linkcardoperation.FieldIdempotencyKeyHash, v)
	return u
}

// UpdateIdempotencyKeyHash sets the "idempotency_key_hash" field to the value that was provided on create.
func (u *LinkCardOperationUpsert) UpdateIdempotencyKeyHash() *LinkCardOperationUpsert {
	u.SetExcluded(linkcardoperation.FieldIdempotencyKeyHash)
	return u
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *LinkCardOperationUpsert) SetRequestFingerprint(v string) *LinkCardOperationUpsert {
	u.Set(linkcardoperation.FieldRequestFingerprint, v)
	return u
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *LinkCardOperationUpsert) UpdateRequestFingerprint() *LinkCardOperationUpsert {
	u.SetExcluded(linkcardoperation.FieldRequestFingerprint)
	return u
}

// SetResponseBody sets the "response_body" field.
func (u *LinkCardOperationUpsert) SetResponseBody(v map[string]interface{}) *LinkCardOperationUpsert {
	u.Set(linkcardoperation.FieldResponseBody, v)
	return u
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *LinkCardOperationUpsert) UpdateResponseBody() *LinkCardOperationUpsert {
	u.SetExcluded(linkcardoperation.FieldResponseBody)
	return u
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *LinkCardOperationUpsert) ClearResponseBody() *LinkCardOperationUpsert {
	u.SetNull(linkcardoperation.FieldResponseBody)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LinkCardOperation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LinkCardOperationUpsertOne) UpdateNewValues() *LinkCardOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(linkcardoperation.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LinkCardOperation.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LinkCardOperationUpsertOne) Ignore() *LinkCardOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LinkCardOperationUpsertOne) DoNothing() *LinkCardOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LinkCardOperationCreate.OnConflict
// documentation for more info.
func (u *LinkCardOperationUpsertOne) Update(set func(*LinkCardOperationUpsert)) *LinkCardOperationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LinkCardOperationUpsert{UpdateSet: update})
	}))
	return u
}

// SetScope sets the "scope" field.
func (u *LinkCardOperationUpsertOne) SetScope(v string) *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *LinkCardOperationUpsertOne) UpdateScope() *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.UpdateScope()
	})
}

// SetActorUserID sets the "actor_user_id" field.
func (u *LinkCardOperationUpsertOne) SetActorUserID(v int64) *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.SetActorUserID(v)
	})
}

// AddActorUserID adds v to the "actor_user_id" field.
func (u *LinkCardOperationUpsertOne) AddActorUserID(v int64) *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.AddActorUserID(v)
	})
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *LinkCardOperationUpsertOne) UpdateActorUserID() *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.UpdateActorUserID()
	})
}

// SetCreatorUserID sets the "creator_user_id" field.
func (u *LinkCardOperationUpsertOne) SetCreatorUserID(v int64) *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.SetCreatorUserID(v)
	})
}

// AddCreatorUserID adds v to the "creator_user_id" field.
func (u *LinkCardOperationUpsertOne) AddCreatorUserID(v int64) *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.AddCreatorUserID(v)
	})
}

// UpdateCreatorUserID sets the "creator_user_id" field to the value that was provided on create.
func (u *LinkCardOperationUpsertOne) UpdateCreatorUserID() *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.UpdateCreatorUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *LinkCardOperationUpsertOne) SetAPIKeyID(v int64) *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *LinkCardOperationUpsertOne) AddAPIKeyID(v int64) *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *LinkCardOperationUpsertOne) UpdateAPIKeyID() *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *LinkCardOperationUpsertOne) ClearAPIKeyID() *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (u *LinkCardOperationUpsertOne) SetIdempotencyKeyHash(v string) *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.SetIdempotencyKeyHash(v)
	})
}

// UpdateIdempotencyKeyHash sets the "idempotency_key_hash" field to the value that was provided on create.
func (u *LinkCardOperationUpsertOne) UpdateIdempotencyKeyHash() *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.UpdateIdempotencyKeyHash()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *LinkCardOperationUpsertOne) SetRequestFingerprint(v string) *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *LinkCardOperationUpsertOne) UpdateRequestFingerprint() *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *LinkCardOperationUpsertOne) SetResponseBody(v map[string]interface{}) *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *LinkCardOperationUpsertOne) UpdateResponseBody() *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.UpdateResponseBody()
	})
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *LinkCardOperationUpsertOne) ClearResponseBody() *LinkCardOperationUpsertOne {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.ClearResponseBody()
	})
}

// Exec executes the query.
func (u *LinkCardOperationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LinkCardOperationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LinkCardOperationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LinkCardOperationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LinkCardOperationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LinkCardOperationCreateBulk is the builder for creating many LinkCardOperation entities in bulk.
type LinkCardOperationCreateBulk struct {
	config
	err      error
	builders []*LinkCardOperationCreate
	conflict []sql.ConflictOption
}

// Save creates the LinkCardOperation entities in the database.
func (_c *LinkCardOperationCreateBulk) Save(ctx context.Context) ([]*LinkCardOperation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LinkCardOperation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LinkCardOperationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LinkCardOperationCreateBulk) SaveX(ctx context.Context) []*LinkCardOperation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCardOperationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCardOperationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LinkCardOperation.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LinkCardOperationUpsert) {
//			SetScope(v+v).
//		}).
//		Exec(ctx)
func (_c *LinkCardOperationCreateBulk) OnConflict(opts ...sql.ConflictOption) *LinkCardOperationUpsertBulk {
	_c.conflict = opts
	return &LinkCardOperationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LinkCardOperation.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LinkCardOperationCreateBulk) OnConflictColumns(columns ...string) *LinkCardOperationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LinkCardOperationUpsertBulk{
		create: _c,
	}
}

// LinkCardOperationUpsertBulk is the builder for "upsert"-ing
// a bulk of LinkCardOperation nodes.
type LinkCardOperationUpsertBulk struct {
	create *LinkCardOperationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LinkCardOperation.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LinkCardOperationUpsertBulk) UpdateNewValues() *LinkCardOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(linkcardoperation.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LinkCardOperation.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LinkCardOperationUpsertBulk) Ignore() *LinkCardOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LinkCardOperationUpsertBulk) DoNothing() *LinkCardOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LinkCardOperationCreateBulk.OnConflict
// documentation for more info.
func (u *LinkCardOperationUpsertBulk) Update(set func(*LinkCardOperationUpsert)) *LinkCardOperationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LinkCardOperationUpsert{UpdateSet: update})
	}))
	return u
}

// SetScope sets the "scope" field.
func (u *LinkCardOperationUpsertBulk) SetScope(v string) *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.SetScope(v)
	})
}

// UpdateScope sets the "scope" field to the value that was provided on create.
func (u *LinkCardOperationUpsertBulk) UpdateScope() *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.UpdateScope()
	})
}

// SetActorUserID sets the "actor_user_id" field.
func (u *LinkCardOperationUpsertBulk) SetActorUserID(v int64) *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.SetActorUserID(v)
	})
}

// AddActorUserID adds v to the "actor_user_id" field.
func (u *LinkCardOperationUpsertBulk) AddActorUserID(v int64) *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.AddActorUserID(v)
	})
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *LinkCardOperationUpsertBulk) UpdateActorUserID() *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.UpdateActorUserID()
	})
}

// SetCreatorUserID sets the "creator_user_id" field.
func (u *LinkCardOperationUpsertBulk) SetCreatorUserID(v int64) *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.SetCreatorUserID(v)
	})
}

// AddCreatorUserID adds v to the "creator_user_id" field.
func (u *LinkCardOperationUpsertBulk) AddCreatorUserID(v int64) *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.AddCreatorUserID(v)
	})
}

// UpdateCreatorUserID sets the "creator_user_id" field to the value that was provided on create.
func (u *LinkCardOperationUpsertBulk) UpdateCreatorUserID() *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.UpdateCreatorUserID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *LinkCardOperationUpsertBulk) SetAPIKeyID(v int64) *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *LinkCardOperationUpsertBulk) AddAPIKeyID(v int64) *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *LinkCardOperationUpsertBulk) UpdateAPIKeyID() *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.UpdateAPIKeyID()
	})
}

// ClearAPIKeyID clears the value of the "api_key_id" field.
func (u *LinkCardOperationUpsertBulk) ClearAPIKeyID() *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.ClearAPIKeyID()
	})
}

// SetIdempotencyKeyHash sets the "idempotency_key_hash" field.
func (u *LinkCardOperationUpsertBulk) SetIdempotencyKeyHash(v string) *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.SetIdempotencyKeyHash(v)
	})
}

// UpdateIdempotencyKeyHash sets the "idempotency_key_hash" field to the value that was provided on create.
func (u *LinkCardOperationUpsertBulk) UpdateIdempotencyKeyHash() *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.UpdateIdempotencyKeyHash()
	})
}

// SetRequestFingerprint sets the "request_fingerprint" field.
func (u *LinkCardOperationUpsertBulk) SetRequestFingerprint(v string) *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.SetRequestFingerprint(v)
	})
}

// UpdateRequestFingerprint sets the "request_fingerprint" field to the value that was provided on create.
func (u *LinkCardOperationUpsertBulk) UpdateRequestFingerprint() *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.UpdateRequestFingerprint()
	})
}

// SetResponseBody sets the "response_body" field.
func (u *LinkCardOperationUpsertBulk) SetResponseBody(v map[string]interface{}) *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.SetResponseBody(v)
	})
}

// UpdateResponseBody sets the "response_body" field to the value that was provided on create.
func (u *LinkCardOperationUpsertBulk) UpdateResponseBody() *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.UpdateResponseBody()
	})
}

// ClearResponseBody clears the value of the "response_body" field.
func (u *LinkCardOperationUpsertBulk) ClearResponseBody() *LinkCardOperationUpsertBulk {
	return u.Update(func(s *LinkCardOperationUpsert) {
		s.ClearResponseBody()
	})
}

// Exec executes the query.
func (u *LinkCardOperationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LinkCardOperationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LinkCardOperationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LinkCardOperationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
