// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/linkcardgroupauthorization"
)

// LinkCardGroupAuthorizationCreate is the builder for creating a LinkCardGroupAuthorization entity.
type LinkCardGroupAuthorizationCreate struct {
	config
	mutation *LinkCardGroupAuthorizationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetGroupID sets the "group_id" field.
func (_c *LinkCardGroupAuthorizationCreate) SetGroupID(v int64) *LinkCardGroupAuthorizationCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *LinkCardGroupAuthorizationCreate) SetEnabled(v bool) *LinkCardGroupAuthorizationCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *LinkCardGroupAuthorizationCreate) SetNillableEnabled(v *bool) *LinkCardGroupAuthorizationCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *LinkCardGroupAuthorizationCreate) SetSortOrder(v int) *LinkCardGroupAuthorizationCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *LinkCardGroupAuthorizationCreate) SetNillableSortOrder(v *int) *LinkCardGroupAuthorizationCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *LinkCardGroupAuthorizationCreate) SetCreatedBy(v int64) *LinkCardGroupAuthorizationCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *LinkCardGroupAuthorizationCreate) SetNillableCreatedBy(v *int64) *LinkCardGroupAuthorizationCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LinkCardGroupAuthorizationCreate) SetCreatedAt(v time.Time) *LinkCardGroupAuthorizationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LinkCardGroupAuthorizationCreate) SetNillableCreatedAt(v *time.Time) *LinkCardGroupAuthorizationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *LinkCardGroupAuthorizationCreate) SetUpdatedAt(v time.Time) *LinkCardGroupAuthorizationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *LinkCardGroupAuthorizationCreate) SetNillableUpdatedAt(v *time.Time) *LinkCardGroupAuthorizationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the LinkCardGroupAuthorizationMutation object of the builder.
func (_c *LinkCardGroupAuthorizationCreate) Mutation() *LinkCardGroupAuthorizationMutation {
	return _c.mutation
}

// Save creates the LinkCardGroupAuthorization in the database.
func (_c *LinkCardGroupAuthorizationCreate) Save(ctx context.Context) (*LinkCardGroupAuthorization, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LinkCardGroupAuthorizationCreate) SaveX(ctx context.Context) *LinkCardGroupAuthorization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCardGroupAuthorizationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCardGroupAuthorizationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LinkCardGroupAuthorizationCreate) defaults() {
	if _, ok := _c.mutation.Enabled(); !ok {
		v := linkcardgroupauthorization.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := linkcardgroupauthorization.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := linkcardgroupauthorization.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := linkcardgroupauthorization.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LinkCardGroupAuthorizationCreate) check() error {
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "LinkCardGroupAuthorization.group_id"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "LinkCardGroupAuthorization.enabled"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "LinkCardGroupAuthorization.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LinkCardGroupAuthorization.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "LinkCardGroupAuthorization.updated_at"`)}
	}
	return nil
}

func (_c *LinkCardGroupAuthorizationCreate) sqlSave(ctx context.Context) (*LinkCardGroupAuthorization, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LinkCardGroupAuthorizationCreate) createSpec() (*LinkCardGroupAuthorization, *sqlgraph.CreateSpec) {
	var (
		_node = &LinkCardGroupAuthorization{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(linkcardgroupauthorization.Table, sqlgraph.NewFieldSpec(linkcardgroupauthorization.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldCreatedBy, field.TypeInt64, value)
		_node.CreatedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LinkCardGroupAuthorization.Create().
//		SetGroupID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LinkCardGroupAuthorizationUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *LinkCardGroupAuthorizationCreate) OnConflict(opts ...sql.ConflictOption) *LinkCardGroupAuthorizationUpsertOne {
	_c.conflict = opts
	return &LinkCardGroupAuthorizationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LinkCardGroupAuthorization.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LinkCardGroupAuthorizationCreate) OnConflictColumns(columns ...string) *LinkCardGroupAuthorizationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LinkCardGroupAuthorizationUpsertOne{
		create: _c,
	}
}

type (
	// LinkCardGroupAuthorizationUpsertOne is the builder for "upsert"-ing
	//  one LinkCardGroupAuthorization node.
	LinkCardGroupAuthorizationUpsertOne struct {
		create *LinkCardGroupAuthorizationCreate
	}

	// LinkCardGroupAuthorizationUpsert is the "OnConflict" setter.
	LinkCardGroupAuthorizationUpsert struct {
		*sql.UpdateSet
	}
)

// SetGroupID sets the "group_id" field.
func (u *LinkCardGroupAuthorizationUpsert) SetGroupID(v int64) *LinkCardGroupAuthorizationUpsert {
	u.Set(linkcardgroupauthorization.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsert) UpdateGroupID() *LinkCardGroupAuthorizationUpsert {
	u.SetExcluded(linkcardgroupauthorization.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *LinkCardGroupAuthorizationUpsert) AddGroupID(v int64) *LinkCardGroupAuthorizationUpsert {
	u.Add(linkcardgroupauthorization.FieldGroupID, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *LinkCardGroupAuthorizationUpsert) SetEnabled(v bool) *LinkCardGroupAuthorizationUpsert {
	u.Set(linkcardgroupauthorization.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsert) UpdateEnabled() *LinkCardGroupAuthorizationUpsert {
	u.SetExcluded(linkcardgroupauthorization.FieldEnabled)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *LinkCardGroupAuthorizationUpsert) SetSortOrder(v int) *LinkCardGroupAuthorizationUpsert {
	u.Set(linkcardgroupauthorization.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsert) UpdateSortOrder() *LinkCardGroupAuthorizationUpsert {
	u.SetExcluded(linkcardgroupauthorization.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *LinkCardGroupAuthorizationUpsert) AddSortOrder(v int) *LinkCardGroupAuthorizationUpsert {
	u.Add(linkcardgroupauthorization.FieldSortOrder, v)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *LinkCardGroupAuthorizationUpsert) SetCreatedBy(v int64) *LinkCardGroupAuthorizationUpsert {
	u.Set(linkcardgroupauthorization.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsert) UpdateCreatedBy() *LinkCardGroupAuthorizationUpsert {
	u.SetExcluded(linkcardgroupauthorization.FieldCreatedBy)
	return u
}

// AddCreatedBy adds v to the "created_by" field.
func (u *LinkCardGroupAuthorizationUpsert) AddCreatedBy(v int64) *LinkCardGroupAuthorizationUpsert {
	u.Add(linkcardgroupauthorization.FieldCreatedBy, v)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *LinkCardGroupAuthorizationUpsert) ClearCreatedBy() *LinkCardGroupAuthorizationUpsert {
	u.SetNull(linkcardgroupauthorization.FieldCreatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LinkCardGroupAuthorizationUpsert) SetUpdatedAt(v time.Time) *LinkCardGroupAuthorizationUpsert {
	u.Set(linkcardgroupauthorization.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsert) UpdateUpdatedAt() *LinkCardGroupAuthorizationUpsert {
	u.SetExcluded(linkcardgroupauthorization.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LinkCardGroupAuthorization.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LinkCardGroupAuthorizationUpsertOne) UpdateNewValues() *LinkCardGroupAuthorizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(linkcardgroupauthorization.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LinkCardGroupAuthorization.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LinkCardGroupAuthorizationUpsertOne) Ignore() *LinkCardGroupAuthorizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LinkCardGroupAuthorizationUpsertOne) DoNothing() *LinkCardGroupAuthorizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LinkCardGroupAuthorizationCreate.OnConflict
// documentation for more info.
func (u *LinkCardGroupAuthorizationUpsertOne) Update(set func(*LinkCardGroupAuthorizationUpsert)) *LinkCardGroupAuthorizationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LinkCardGroupAuthorizationUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *LinkCardGroupAuthorizationUpsertOne) SetGroupID(v int64) *LinkCardGroupAuthorizationUpsertOne {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *LinkCardGroupAuthorizationUpsertOne) AddGroupID(v int64) *LinkCardGroupAuthorizationUpsertOne {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsertOne) UpdateGroupID() *LinkCardGroupAuthorizationUpsertOne {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.UpdateGroupID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *LinkCardGroupAuthorizationUpsertOne) SetEnabled(v bool) *LinkCardGroupAuthorizationUpsertOne {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsertOne) UpdateEnabled() *LinkCardGroupAuthorizationUpsertOne {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *LinkCardGroupAuthorizationUpsertOne) SetSortOrder(v int) *LinkCardGroupAuthorizationUpsertOne {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *LinkCardGroupAuthorizationUpsertOne) AddSortOrder(v int) *LinkCardGroupAuthorizationUpsertOne {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsertOne) UpdateSortOrder() *LinkCardGroupAuthorizationUpsertOne {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.UpdateSortOrder()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *LinkCardGroupAuthorizationUpsertOne) SetCreatedBy(v int64) *LinkCardGroupAuthorizationUpsertOne {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *LinkCardGroupAuthorizationUpsertOne) AddCreatedBy(v int64) *LinkCardGroupAuthorizationUpsertOne {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsertOne) UpdateCreatedBy() *LinkCardGroupAuthorizationUpsertOne {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *LinkCardGroupAuthorizationUpsertOne) ClearCreatedBy() *LinkCardGroupAuthorizationUpsertOne {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LinkCardGroupAuthorizationUpsertOne) SetUpdatedAt(v time.Time) *LinkCardGroupAuthorizationUpsertOne {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsertOne) UpdateUpdatedAt() *LinkCardGroupAuthorizationUpsertOne {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LinkCardGroupAuthorizationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LinkCardGroupAuthorizationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LinkCardGroupAuthorizationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LinkCardGroupAuthorizationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LinkCardGroupAuthorizationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LinkCardGroupAuthorizationCreateBulk is the builder for creating many LinkCardGroupAuthorization entities in bulk.
type LinkCardGroupAuthorizationCreateBulk struct {
	config
	err      error
	builders []*LinkCardGroupAuthorizationCreate
	conflict []sql.ConflictOption
}

// Save creates the LinkCardGroupAuthorization entities in the database.
func (_c *LinkCardGroupAuthorizationCreateBulk) Save(ctx context.Context) ([]*LinkCardGroupAuthorization, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LinkCardGroupAuthorization, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LinkCardGroupAuthorizationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LinkCardGroupAuthorizationCreateBulk) SaveX(ctx context.Context) []*LinkCardGroupAuthorization {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCardGroupAuthorizationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCardGroupAuthorizationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LinkCardGroupAuthorization.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LinkCardGroupAuthorizationUpsert) {
//			SetGroupID(v+v).
//		}).
//		Exec(ctx)
func (_c *LinkCardGroupAuthorizationCreateBulk) OnConflict(opts ...sql.ConflictOption) *LinkCardGroupAuthorizationUpsertBulk {
	_c.conflict = opts
	return &LinkCardGroupAuthorizationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LinkCardGroupAuthorization.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LinkCardGroupAuthorizationCreateBulk) OnConflictColumns(columns ...string) *LinkCardGroupAuthorizationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LinkCardGroupAuthorizationUpsertBulk{
		create: _c,
	}
}

// LinkCardGroupAuthorizationUpsertBulk is the builder for "upsert"-ing
// a bulk of LinkCardGroupAuthorization nodes.
type LinkCardGroupAuthorizationUpsertBulk struct {
	create *LinkCardGroupAuthorizationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LinkCardGroupAuthorization.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LinkCardGroupAuthorizationUpsertBulk) UpdateNewValues() *LinkCardGroupAuthorizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(linkcardgroupauthorization.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LinkCardGroupAuthorization.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LinkCardGroupAuthorizationUpsertBulk) Ignore() *LinkCardGroupAuthorizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LinkCardGroupAuthorizationUpsertBulk) DoNothing() *LinkCardGroupAuthorizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LinkCardGroupAuthorizationCreateBulk.OnConflict
// documentation for more info.
func (u *LinkCardGroupAuthorizationUpsertBulk) Update(set func(*LinkCardGroupAuthorizationUpsert)) *LinkCardGroupAuthorizationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LinkCardGroupAuthorizationUpsert{UpdateSet: update})
	}))
	return u
}

// SetGroupID sets the "group_id" field.
func (u *LinkCardGroupAuthorizationUpsertBulk) SetGroupID(v int64) *LinkCardGroupAuthorizationUpsertBulk {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *LinkCardGroupAuthorizationUpsertBulk) AddGroupID(v int64) *LinkCardGroupAuthorizationUpsertBulk {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsertBulk) UpdateGroupID() *LinkCardGroupAuthorizationUpsertBulk {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.UpdateGroupID()
	})
}

// SetEnabled sets the "enabled" field.
func (u *LinkCardGroupAuthorizationUpsertBulk) SetEnabled(v bool) *LinkCardGroupAuthorizationUpsertBulk {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsertBulk) UpdateEnabled() *LinkCardGroupAuthorizationUpsertBulk {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.UpdateEnabled()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *LinkCardGroupAuthorizationUpsertBulk) SetSortOrder(v int) *LinkCardGroupAuthorizationUpsertBulk {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *LinkCardGroupAuthorizationUpsertBulk) AddSortOrder(v int) *LinkCardGroupAuthorizationUpsertBulk {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsertBulk) UpdateSortOrder() *LinkCardGroupAuthorizationUpsertBulk {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.UpdateSortOrder()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *LinkCardGroupAuthorizationUpsertBulk) SetCreatedBy(v int64) *LinkCardGroupAuthorizationUpsertBulk {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.SetCreatedBy(v)
	})
}

// AddCreatedBy adds v to the "created_by" field.
func (u *LinkCardGroupAuthorizationUpsertBulk) AddCreatedBy(v int64) *LinkCardGroupAuthorizationUpsertBulk {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.AddCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsertBulk) UpdateCreatedBy() *LinkCardGroupAuthorizationUpsertBulk {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *LinkCardGroupAuthorizationUpsertBulk) ClearCreatedBy() *LinkCardGroupAuthorizationUpsertBulk {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *LinkCardGroupAuthorizationUpsertBulk) SetUpdatedAt(v time.Time) *LinkCardGroupAuthorizationUpsertBulk {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *LinkCardGroupAuthorizationUpsertBulk) UpdateUpdatedAt() *LinkCardGroupAuthorizationUpsertBulk {
	return u.Update(func(s *LinkCardGroupAuthorizationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *LinkCardGroupAuthorizationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LinkCardGroupAuthorizationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LinkCardGroupAuthorizationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LinkCardGroupAuthorizationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
