// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/linkcardledger"
)

// LinkCardLedger is the model entity for the LinkCardLedger schema.
type LinkCardLedger struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// OperationID holds the value of the "operation_id" field.
	OperationID *int64 `json:"operation_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// CreatorUserID holds the value of the "creator_user_id" field.
	CreatorUserID int64 `json:"creator_user_id,omitempty"`
	// EntryType holds the value of the "entry_type" field.
	EntryType string `json:"entry_type,omitempty"`
	// ReserveDelta holds the value of the "reserve_delta" field.
	ReserveDelta float64 `json:"reserve_delta,omitempty"`
	// CreatorBalanceDelta holds the value of the "creator_balance_delta" field.
	CreatorBalanceDelta float64 `json:"creator_balance_delta,omitempty"`
	// QuotaBefore holds the value of the "quota_before" field.
	QuotaBefore float64 `json:"quota_before,omitempty"`
	// QuotaAfter holds the value of the "quota_after" field.
	QuotaAfter float64 `json:"quota_after,omitempty"`
	// QuotaUsedBefore holds the value of the "quota_used_before" field.
	QuotaUsedBefore float64 `json:"quota_used_before,omitempty"`
	// QuotaUsedAfter holds the value of the "quota_used_after" field.
	QuotaUsedAfter float64 `json:"quota_used_after,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID *string `json:"request_id,omitempty"`
	// ActorUserID holds the value of the "actor_user_id" field.
	ActorUserID *int64 `json:"actor_user_id,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata map[string]interface{} `json:"metadata,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*LinkCardLedger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case linkcardledger.FieldMetadata:
			values[i] = new([]byte)
		case linkcardledger.FieldReserveDelta, linkcardledger.FieldCreatorBalanceDelta, linkcardledger.FieldQuotaBefore, linkcardledger.FieldQuotaAfter, linkcardledger.FieldQuotaUsedBefore, linkcardledger.FieldQuotaUsedAfter:
			values[i] = new(sql.NullFloat64)
		case linkcardledger.FieldID, linkcardledger.FieldOperationID, linkcardledger.FieldAPIKeyID, linkcardledger.FieldCreatorUserID, linkcardledger.FieldActorUserID:
			values[i] = new(sql.NullInt64)
		case linkcardledger.FieldEntryType, linkcardledger.FieldRequestID, linkcardledger.FieldReason:
			values[i] = new(sql.NullString)
		case linkcardledger.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the LinkCardLedger fields.
func (_m *LinkCardLedger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case linkcardledger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case linkcardledger.FieldOperationID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field operation_id", values[i])
			} else if value.Valid {
				_m.OperationID = new(int64)
				*_m.OperationID = value.Int64
			}
		case linkcardledger.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case linkcardledger.FieldCreatorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field creator_user_id", values[i])
			} else if value.Valid {
				_m.CreatorUserID = value.Int64
			}
		case linkcardledger.FieldEntryType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entry_type", values[i])
			} else if value.Valid {
				_m.EntryType = value.String
			}
		case linkcardledger.FieldReserveDelta:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field reserve_delta", values[i])
			} else if value.Valid {
				_m.ReserveDelta = value.Float64
			}
		case linkcardledger.FieldCreatorBalanceDelta:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field creator_balance_delta", values[i])
			} else if value.Valid {
				_m.CreatorBalanceDelta = value.Float64
			}
		case linkcardledger.FieldQuotaBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quota_before", values[i])
			} else if value.Valid {
				_m.QuotaBefore = value.Float64
			}
		case linkcardledger.FieldQuotaAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quota_after", values[i])
			} else if value.Valid {
				_m.QuotaAfter = value.Float64
			}
		case linkcardledger.FieldQuotaUsedBefore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quota_used_before", values[i])
			} else if value.Valid {
				_m.QuotaUsedBefore = value.Float64
			}
		case linkcardledger.FieldQuotaUsedAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field quota_used_after", values[i])
			} else if value.Valid {
				_m.QuotaUsedAfter = value.Float64
			}
		case linkcardledger.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(string)
				*_m.RequestID = value.String
			}
		case linkcardledger.FieldActorUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actor_user_id", values[i])
			} else if value.Valid {
				_m.ActorUserID = new(int64)
				*_m.ActorUserID = value.Int64
			}
		case linkcardledger.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case linkcardledger.FieldMetadata:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Metadata); err != nil {
					return fmt.Errorf("unmarshal field metadata: %w", err)
				}
			}
		case linkcardledger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the LinkCardLedger.
// This includes values selected through modifiers, order, etc.
func (_m *LinkCardLedger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this LinkCardLedger.
// Note that you need to call LinkCardLedger.Unwrap() before calling this method if this LinkCardLedger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *LinkCardLedger) Update() *LinkCardLedgerUpdateOne {
	return NewLinkCardLedgerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the LinkCardLedger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *LinkCardLedger) Unwrap() *LinkCardLedger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: LinkCardLedger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *LinkCardLedger) String() string {
	var builder strings.Builder
	builder.WriteString("LinkCardLedger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.OperationID; v != nil {
		builder.WriteString("operation_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("creator_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatorUserID))
	builder.WriteString(", ")
	builder.WriteString("entry_type=")
	builder.WriteString(_m.EntryType)
	builder.WriteString(", ")
	builder.WriteString("reserve_delta=")
	builder.WriteString(fmt.Sprintf("%v", _m.ReserveDelta))
	builder.WriteString(", ")
	builder.WriteString("creator_balance_delta=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatorBalanceDelta))
	builder.WriteString(", ")
	builder.WriteString("quota_before=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaBefore))
	builder.WriteString(", ")
	builder.WriteString("quota_after=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaAfter))
	builder.WriteString(", ")
	builder.WriteString("quota_used_before=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaUsedBefore))
	builder.WriteString(", ")
	builder.WriteString("quota_used_after=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuotaUsedAfter))
	builder.WriteString(", ")
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ActorUserID; v != nil {
		builder.WriteString("actor_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("metadata=")
	builder.WriteString(fmt.Sprintf("%v", _m.Metadata))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LinkCardLedgers is a parsable slice of LinkCardLedger.
type LinkCardLedgers []*LinkCardLedger
