// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/linkcardledger"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LinkCardLedgerUpdate is the builder for updating LinkCardLedger entities.
type LinkCardLedgerUpdate struct {
	config
	hooks    []Hook
	mutation *LinkCardLedgerMutation
}

// Where appends a list predicates to the LinkCardLedgerUpdate builder.
func (_u *LinkCardLedgerUpdate) Where(ps ...predicate.LinkCardLedger) *LinkCardLedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOperationID sets the "operation_id" field.
func (_u *LinkCardLedgerUpdate) SetOperationID(v int64) *LinkCardLedgerUpdate {
	_u.mutation.ResetOperationID()
	_u.mutation.SetOperationID(v)
	return _u
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (_u *LinkCardLedgerUpdate) SetNillableOperationID(v *int64) *LinkCardLedgerUpdate {
	if v != nil {
		_u.SetOperationID(*v)
	}
	return _u
}

// AddOperationID adds value to the "operation_id" field.
func (_u *LinkCardLedgerUpdate) AddOperationID(v int64) *LinkCardLedgerUpdate {
	_u.mutation.AddOperationID(v)
	return _u
}

// ClearOperationID clears the value of the "operation_id" field.
func (_u *LinkCardLedgerUpdate) ClearOperationID() *LinkCardLedgerUpdate {
	_u.mutation.ClearOperationID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *LinkCardLedgerUpdate) SetAPIKeyID(v int64) *LinkCardLedgerUpdate {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *LinkCardLedgerUpdate) SetNillableAPIKeyID(v *int64) *LinkCardLedgerUpdate {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *LinkCardLedgerUpdate) AddAPIKeyID(v int64) *LinkCardLedgerUpdate {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetCreatorUserID sets the "creator_user_id" field.
func (_u *LinkCardLedgerUpdate) SetCreatorUserID(v int64) *LinkCardLedgerUpdate {
	_u.mutation.ResetCreatorUserID()
	_u.mutation.SetCreatorUserID(v)
	return _u
}

// SetNillableCreatorUserID sets the "creator_user_id" field if the given value is not nil.
func (_u *LinkCardLedgerUpdate) SetNillableCreatorUserID(v *int64) *LinkCardLedgerUpdate {
	if v != nil {
		_u.SetCreatorUserID(*v)
	}
	return _u
}

// AddCreatorUserID adds value to the "creator_user_id" field.
func (_u *LinkCardLedgerUpdate) AddCreatorUserID(v int64) *LinkCardLedgerUpdate {
	_u.mutation.AddCreatorUserID(v)
	return _u
}

// SetEntryType sets the "entry_type" field.
func (_u *LinkCardLedgerUpdate) SetEntryType(v string) *LinkCardLedgerUpdate {
	_u.mutation.SetEntryType(v)
	return _u
}

// SetNillableEntryType sets the "entry_type" field if the given value is not nil.
func (_u *LinkCardLedgerUpdate) SetNillableEntryType(v *string) *LinkCardLedgerUpdate {
	if v != nil {
		_u.SetEntryType(*v)
	}
	return _u
}

// SetReserveDelta sets the "reserve_delta" field.
func (_u *LinkCardLedgerUpdate) SetReserveDelta(v float64) *LinkCardLedgerUpdate {
	_u.mutation.ResetReserveDelta()
	_u.mutation.SetReserveDelta(v)
	return _u
}

// SetNillableReserveDelta sets the "reserve_delta" field if the given value is not nil.
func (_u *LinkCardLedgerUpdate) SetNillableReserveDelta(v *float64) *LinkCardLedgerUpdate {
	if v != nil {
		_u.SetReserveDelta(*v)
	}
	return _u
}

// AddReserveDelta adds value to the "reserve_delta" field.
func (_u *LinkCardLedgerUpdate) AddReserveDelta(v float64) *LinkCardLedgerUpdate {
	_u.mutation.AddReserveDelta(v)
	return _u
}

// SetCreatorBalanceDelta sets the "creator_balance_delta" field.
func (_u *LinkCardLedgerUpdate) SetCreatorBalanceDelta(v float64) *LinkCardLedgerUpdate {
	_u.mutation.ResetCreatorBalanceDelta()
	_u.mutation.SetCreatorBalanceDelta(v)
	return _u
}

// SetNillableCreatorBalanceDelta sets the "creator_balance_delta" field if the given value is not nil.
func (_u *LinkCardLedgerUpdate) SetNillableCreatorBalanceDelta(v *float64) *LinkCardLedgerUpdate {
	if v != nil {
		_u.SetCreatorBalanceDelta(*v)
	}
	return _u
}

// AddCreatorBalanceDelta adds value to the "creator_balance_delta" field.
func (_u *LinkCardLedgerUpdate) AddCreatorBalanceDelta(v float64) *LinkCardLedgerUpdate {
	_u.mutation.AddCreatorBalanceDelta(v)
	return _u
}

// SetQuotaBefore sets the "quota_before" field.
func (_u *LinkCardLedgerUpdate) SetQuotaBefore(v float64) *LinkCardLedgerUpdate {
	_u.mutation.ResetQuotaBefore()
	_u.mutation.SetQuotaBefore(v)
	return _u
}

// SetNillableQuotaBefore sets the "quota_before" field if the given value is not nil.
func (_u *LinkCardLedgerUpdate) SetNillableQuotaBefore(v *float64) *LinkCardLedgerUpdate {
	if v != nil {
		_u.SetQuotaBefore(*v)
	}
	return _u
}

// AddQuotaBefore adds value to the "quota_before" field.
func (_u *LinkCardLedgerUpdate) AddQuotaBefore(v float64) *LinkCardLedgerUpdate {
	_u.mutation.AddQuotaBefore(v)
	return _u
}

// SetQuotaAfter sets the "quota_after" field.
func (_u *LinkCardLedgerUpdate) SetQuotaAfter(v float64) *LinkCardLedgerUpdate {
	_u.mutation.ResetQuotaAfter()
	_u.mutation.SetQuotaAfter(v)
	return _u
}

// SetNillableQuotaAfter sets the "quota_after" field if the given value is not nil.
func (_u *LinkCardLedgerUpdate) SetNillableQuotaAfter(v *float64) *LinkCardLedgerUpdate {
	if v != nil {
		_u.SetQuotaAfter(*v)
	}
	return _u
}

// AddQuotaAfter adds value to the "quota_after" field.
func (_u *LinkCardLedgerUpdate) AddQuotaAfter(v float64) *LinkCardLedgerUpdate {
	_u.mutation.AddQuotaAfter(v)
	return _u
}

// SetQuotaUsedBefore sets the "quota_used_before" field.
func (_u *LinkCardLedgerUpdate) SetQuotaUsedBefore(v float64) *LinkCardLedgerUpdate {
	_u.mutation.ResetQuotaUsedBefore()
	_u.mutation.SetQuotaUsedBefore(v)
	return _u
}

// SetNillableQuotaUsedBefore sets the "quota_used_before" field if the given value is not nil.
func (_u *LinkCardLedgerUpdate) SetNillableQuotaUsedBefore(v *float64) *LinkCardLedgerUpdate {
	if v != nil {
		_u.SetQuotaUsedBefore(*v)
	}
	return _u
}

// AddQuotaUsedBefore adds value to the "quota_used_before" field.
func (_u *LinkCardLedgerUpdate) AddQuotaUsedBefore(v float64) *LinkCardLedgerUpdate {
	_u.mutation.AddQuotaUsedBefore(v)
	return _u
}

// SetQuotaUsedAfter sets the "quota_used_after" field.
func (_u *LinkCardLedgerUpdate) SetQuotaUsedAfter(v float64) *LinkCardLedgerUpdate {
	_u.mutation.ResetQuotaUsedAfter()
	_u.mutation.SetQuotaUsedAfter(v)
	return _u
}

// SetNillableQuotaUsedAfter sets the "quota_used_after" field if the given value is not nil.
func (_u *LinkCardLedgerUpdate) SetNillableQuotaUsedAfter(v *float64) *LinkCardLedgerUpdate {
	if v != nil {
		_u.SetQuotaUsedAfter(*v)
	}
	return _u
}

// AddQuotaUsedAfter adds value to the "quota_used_after" field.
func (_u *LinkCardLedgerUpdate) AddQuotaUsedAfter(v float64) *LinkCardLedgerUpdate {
	_u.mutation.AddQuotaUsedAfter(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *LinkCardLedgerUpdate) SetRequestID(v string) *LinkCardLedgerUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *LinkCardLedgerUpdate) SetNillableRequestID(v *string) *LinkCardLedgerUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *LinkCardLedgerUpdate) ClearRequestID() *LinkCardLedgerUpdate {
	_u.mutation.ClearRequestID()
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *LinkCardLedgerUpdate) SetActorUserID(v int64) *LinkCardLedgerUpdate {
	_u.mutation.ResetActorUserID()
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *LinkCardLedgerUpdate) SetNillableActorUserID(v *int64) *LinkCardLedgerUpdate {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// AddActorUserID adds value to the "actor_user_id" field.
func (_u *LinkCardLedgerUpdate) AddActorUserID(v int64) *LinkCardLedgerUpdate {
	_u.mutation.AddActorUserID(v)
	return _u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (_u *LinkCardLedgerUpdate) ClearActorUserID() *LinkCardLedgerUpdate {
	_u.mutation.ClearActorUserID()
	return _u
}

// SetReason sets the "reason" field.
func (_u *LinkCardLedgerUpdate) SetReason(v string) *LinkCardLedgerUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *LinkCardLedgerUpdate) SetNillableReason(v *string) *LinkCardLedgerUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *LinkCardLedgerUpdate) SetMetadata(v map[string]interface{}) *LinkCardLedgerUpdate {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *LinkCardLedgerUpdate) ClearMetadata() *LinkCardLedgerUpdate {
	_u.mutation.ClearMetadata()
	return _u
}

// Mutation returns the LinkCardLedgerMutation object of the builder.
func (_u *LinkCardLedgerUpdate) Mutation() *LinkCardLedgerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LinkCardLedgerUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkCardLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LinkCardLedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkCardLedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LinkCardLedgerUpdate) check() error {
	if v, ok := _u.mutation.EntryType(); ok {
		if err := linkcardledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "LinkCardLedger.entry_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := linkcardledger.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "LinkCardLedger.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := linkcardledger.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "LinkCardLedger.reason": %w`, err)}
		}
	}
	return nil
}

func (_u *LinkCardLedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(linkcardledger.Table, linkcardledger.Columns, sqlgraph.NewFieldSpec(linkcardledger.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperationID(); ok {
		_spec.SetField(linkcardledger.FieldOperationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperationID(); ok {
		_spec.AddField(linkcardledger.FieldOperationID, field.TypeInt64, value)
	}
	if _u.mutation.OperationIDCleared() {
		_spec.ClearField(linkcardledger.FieldOperationID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(linkcardledger.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(linkcardledger.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatorUserID(); ok {
		_spec.SetField(linkcardledger.FieldCreatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatorUserID(); ok {
		_spec.AddField(linkcardledger.FieldCreatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EntryType(); ok {
		_spec.SetField(linkcardledger.FieldEntryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReserveDelta(); ok {
		_spec.SetField(linkcardledger.FieldReserveDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReserveDelta(); ok {
		_spec.AddField(linkcardledger.FieldReserveDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatorBalanceDelta(); ok {
		_spec.SetField(linkcardledger.FieldCreatorBalanceDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreatorBalanceDelta(); ok {
		_spec.AddField(linkcardledger.FieldCreatorBalanceDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaBefore(); ok {
		_spec.SetField(linkcardledger.FieldQuotaBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaBefore(); ok {
		_spec.AddField(linkcardledger.FieldQuotaBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaAfter(); ok {
		_spec.SetField(linkcardledger.FieldQuotaAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaAfter(); ok {
		_spec.AddField(linkcardledger.FieldQuotaAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaUsedBefore(); ok {
		_spec.SetField(linkcardledger.FieldQuotaUsedBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsedBefore(); ok {
		_spec.AddField(linkcardledger.FieldQuotaUsedBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaUsedAfter(); ok {
		_spec.SetField(linkcardledger.FieldQuotaUsedAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsedAfter(); ok {
		_spec.AddField(linkcardledger.FieldQuotaUsedAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(linkcardledger.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(linkcardledger.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.ActorUserID(); ok {
		_spec.SetField(linkcardledger.FieldActorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActorUserID(); ok {
		_spec.AddField(linkcardledger.FieldActorUserID, field.TypeInt64, value)
	}
	if _u.mutation.ActorUserIDCleared() {
		_spec.ClearField(linkcardledger.FieldActorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(linkcardledger.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(linkcardledger.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(linkcardledger.FieldMetadata, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{linkcardledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LinkCardLedgerUpdateOne is the builder for updating a single LinkCardLedger entity.
type LinkCardLedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LinkCardLedgerMutation
}

// SetOperationID sets the "operation_id" field.
func (_u *LinkCardLedgerUpdateOne) SetOperationID(v int64) *LinkCardLedgerUpdateOne {
	_u.mutation.ResetOperationID()
	_u.mutation.SetOperationID(v)
	return _u
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (_u *LinkCardLedgerUpdateOne) SetNillableOperationID(v *int64) *LinkCardLedgerUpdateOne {
	if v != nil {
		_u.SetOperationID(*v)
	}
	return _u
}

// AddOperationID adds value to the "operation_id" field.
func (_u *LinkCardLedgerUpdateOne) AddOperationID(v int64) *LinkCardLedgerUpdateOne {
	_u.mutation.AddOperationID(v)
	return _u
}

// ClearOperationID clears the value of the "operation_id" field.
func (_u *LinkCardLedgerUpdateOne) ClearOperationID() *LinkCardLedgerUpdateOne {
	_u.mutation.ClearOperationID()
	return _u
}

// SetAPIKeyID sets the "api_key_id" field.
func (_u *LinkCardLedgerUpdateOne) SetAPIKeyID(v int64) *LinkCardLedgerUpdateOne {
	_u.mutation.ResetAPIKeyID()
	_u.mutation.SetAPIKeyID(v)
	return _u
}

// SetNillableAPIKeyID sets the "api_key_id" field if the given value is not nil.
func (_u *LinkCardLedgerUpdateOne) SetNillableAPIKeyID(v *int64) *LinkCardLedgerUpdateOne {
	if v != nil {
		_u.SetAPIKeyID(*v)
	}
	return _u
}

// AddAPIKeyID adds value to the "api_key_id" field.
func (_u *LinkCardLedgerUpdateOne) AddAPIKeyID(v int64) *LinkCardLedgerUpdateOne {
	_u.mutation.AddAPIKeyID(v)
	return _u
}

// SetCreatorUserID sets the "creator_user_id" field.
func (_u *LinkCardLedgerUpdateOne) SetCreatorUserID(v int64) *LinkCardLedgerUpdateOne {
	_u.mutation.ResetCreatorUserID()
	_u.mutation.SetCreatorUserID(v)
	return _u
}

// SetNillableCreatorUserID sets the "creator_user_id" field if the given value is not nil.
func (_u *LinkCardLedgerUpdateOne) SetNillableCreatorUserID(v *int64) *LinkCardLedgerUpdateOne {
	if v != nil {
		_u.SetCreatorUserID(*v)
	}
	return _u
}

// AddCreatorUserID adds value to the "creator_user_id" field.
func (_u *LinkCardLedgerUpdateOne) AddCreatorUserID(v int64) *LinkCardLedgerUpdateOne {
	_u.mutation.AddCreatorUserID(v)
	return _u
}

// SetEntryType sets the "entry_type" field.
func (_u *LinkCardLedgerUpdateOne) SetEntryType(v string) *LinkCardLedgerUpdateOne {
	_u.mutation.SetEntryType(v)
	return _u
}

// SetNillableEntryType sets the "entry_type" field if the given value is not nil.
func (_u *LinkCardLedgerUpdateOne) SetNillableEntryType(v *string) *LinkCardLedgerUpdateOne {
	if v != nil {
		_u.SetEntryType(*v)
	}
	return _u
}

// SetReserveDelta sets the "reserve_delta" field.
func (_u *LinkCardLedgerUpdateOne) SetReserveDelta(v float64) *LinkCardLedgerUpdateOne {
	_u.mutation.ResetReserveDelta()
	_u.mutation.SetReserveDelta(v)
	return _u
}

// SetNillableReserveDelta sets the "reserve_delta" field if the given value is not nil.
func (_u *LinkCardLedgerUpdateOne) SetNillableReserveDelta(v *float64) *LinkCardLedgerUpdateOne {
	if v != nil {
		_u.SetReserveDelta(*v)
	}
	return _u
}

// AddReserveDelta adds value to the "reserve_delta" field.
func (_u *LinkCardLedgerUpdateOne) AddReserveDelta(v float64) *LinkCardLedgerUpdateOne {
	_u.mutation.AddReserveDelta(v)
	return _u
}

// SetCreatorBalanceDelta sets the "creator_balance_delta" field.
func (_u *LinkCardLedgerUpdateOne) SetCreatorBalanceDelta(v float64) *LinkCardLedgerUpdateOne {
	_u.mutation.ResetCreatorBalanceDelta()
	_u.mutation.SetCreatorBalanceDelta(v)
	return _u
}

// SetNillableCreatorBalanceDelta sets the "creator_balance_delta" field if the given value is not nil.
func (_u *LinkCardLedgerUpdateOne) SetNillableCreatorBalanceDelta(v *float64) *LinkCardLedgerUpdateOne {
	if v != nil {
		_u.SetCreatorBalanceDelta(*v)
	}
	return _u
}

// AddCreatorBalanceDelta adds value to the "creator_balance_delta" field.
func (_u *LinkCardLedgerUpdateOne) AddCreatorBalanceDelta(v float64) *LinkCardLedgerUpdateOne {
	_u.mutation.AddCreatorBalanceDelta(v)
	return _u
}

// SetQuotaBefore sets the "quota_before" field.
func (_u *LinkCardLedgerUpdateOne) SetQuotaBefore(v float64) *LinkCardLedgerUpdateOne {
	_u.mutation.ResetQuotaBefore()
	_u.mutation.SetQuotaBefore(v)
	return _u
}

// SetNillableQuotaBefore sets the "quota_before" field if the given value is not nil.
func (_u *LinkCardLedgerUpdateOne) SetNillableQuotaBefore(v *float64) *LinkCardLedgerUpdateOne {
	if v != nil {
		_u.SetQuotaBefore(*v)
	}
	return _u
}

// AddQuotaBefore adds value to the "quota_before" field.
func (_u *LinkCardLedgerUpdateOne) AddQuotaBefore(v float64) *LinkCardLedgerUpdateOne {
	_u.mutation.AddQuotaBefore(v)
	return _u
}

// SetQuotaAfter sets the "quota_after" field.
func (_u *LinkCardLedgerUpdateOne) SetQuotaAfter(v float64) *LinkCardLedgerUpdateOne {
	_u.mutation.ResetQuotaAfter()
	_u.mutation.SetQuotaAfter(v)
	return _u
}

// SetNillableQuotaAfter sets the "quota_after" field if the given value is not nil.
func (_u *LinkCardLedgerUpdateOne) SetNillableQuotaAfter(v *float64) *LinkCardLedgerUpdateOne {
	if v != nil {
		_u.SetQuotaAfter(*v)
	}
	return _u
}

// AddQuotaAfter adds value to the "quota_after" field.
func (_u *LinkCardLedgerUpdateOne) AddQuotaAfter(v float64) *LinkCardLedgerUpdateOne {
	_u.mutation.AddQuotaAfter(v)
	return _u
}

// SetQuotaUsedBefore sets the "quota_used_before" field.
func (_u *LinkCardLedgerUpdateOne) SetQuotaUsedBefore(v float64) *LinkCardLedgerUpdateOne {
	_u.mutation.ResetQuotaUsedBefore()
	_u.mutation.SetQuotaUsedBefore(v)
	return _u
}

// SetNillableQuotaUsedBefore sets the "quota_used_before" field if the given value is not nil.
func (_u *LinkCardLedgerUpdateOne) SetNillableQuotaUsedBefore(v *float64) *LinkCardLedgerUpdateOne {
	if v != nil {
		_u.SetQuotaUsedBefore(*v)
	}
	return _u
}

// AddQuotaUsedBefore adds value to the "quota_used_before" field.
func (_u *LinkCardLedgerUpdateOne) AddQuotaUsedBefore(v float64) *LinkCardLedgerUpdateOne {
	_u.mutation.AddQuotaUsedBefore(v)
	return _u
}

// SetQuotaUsedAfter sets the "quota_used_after" field.
func (_u *LinkCardLedgerUpdateOne) SetQuotaUsedAfter(v float64) *LinkCardLedgerUpdateOne {
	_u.mutation.ResetQuotaUsedAfter()
	_u.mutation.SetQuotaUsedAfter(v)
	return _u
}

// SetNillableQuotaUsedAfter sets the "quota_used_after" field if the given value is not nil.
func (_u *LinkCardLedgerUpdateOne) SetNillableQuotaUsedAfter(v *float64) *LinkCardLedgerUpdateOne {
	if v != nil {
		_u.SetQuotaUsedAfter(*v)
	}
	return _u
}

// AddQuotaUsedAfter adds value to the "quota_used_after" field.
func (_u *LinkCardLedgerUpdateOne) AddQuotaUsedAfter(v float64) *LinkCardLedgerUpdateOne {
	_u.mutation.AddQuotaUsedAfter(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *LinkCardLedgerUpdateOne) SetRequestID(v string) *LinkCardLedgerUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *LinkCardLedgerUpdateOne) SetNillableRequestID(v *string) *LinkCardLedgerUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// ClearRequestID clears the value of the "request_id" field.
func (_u *LinkCardLedgerUpdateOne) ClearRequestID() *LinkCardLedgerUpdateOne {
	_u.mutation.ClearRequestID()
	return _u
}

// SetActorUserID sets the "actor_user_id" field.
func (_u *LinkCardLedgerUpdateOne) SetActorUserID(v int64) *LinkCardLedgerUpdateOne {
	_u.mutation.ResetActorUserID()
	_u.mutation.SetActorUserID(v)
	return _u
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_u *LinkCardLedgerUpdateOne) SetNillableActorUserID(v *int64) *LinkCardLedgerUpdateOne {
	if v != nil {
		_u.SetActorUserID(*v)
	}
	return _u
}

// AddActorUserID adds value to the "actor_user_id" field.
func (_u *LinkCardLedgerUpdateOne) AddActorUserID(v int64) *LinkCardLedgerUpdateOne {
	_u.mutation.AddActorUserID(v)
	return _u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (_u *LinkCardLedgerUpdateOne) ClearActorUserID() *LinkCardLedgerUpdateOne {
	_u.mutation.ClearActorUserID()
	return _u
}

// SetReason sets the "reason" field.
func (_u *LinkCardLedgerUpdateOne) SetReason(v string) *LinkCardLedgerUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *LinkCardLedgerUpdateOne) SetNillableReason(v *string) *LinkCardLedgerUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetMetadata sets the "metadata" field.
func (_u *LinkCardLedgerUpdateOne) SetMetadata(v map[string]interface{}) *LinkCardLedgerUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
}

// ClearMetadata clears the value of the "metadata" field.
func (_u *LinkCardLedgerUpdateOne) ClearMetadata() *LinkCardLedgerUpdateOne {
	_u.mutation.ClearMetadata()
	return _u
}

// Mutation returns the LinkCardLedgerMutation object of the builder.
func (_u *LinkCardLedgerUpdateOne) Mutation() *LinkCardLedgerMutation {
	return _u.mutation
}

// Where appends a list predicates to the LinkCardLedgerUpdate builder.
func (_u *LinkCardLedgerUpdateOne) Where(ps ...predicate.LinkCardLedger) *LinkCardLedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LinkCardLedgerUpdateOne) Select(field string, fields ...string) *LinkCardLedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LinkCardLedger entity.
func (_u *LinkCardLedgerUpdateOne) Save(ctx context.Context) (*LinkCardLedger, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkCardLedgerUpdateOne) SaveX(ctx context.Context) *LinkCardLedger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LinkCardLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkCardLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LinkCardLedgerUpdateOne) check() error {
	if v, ok := _u.mutation.EntryType(); ok {
		if err := linkcardledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "LinkCardLedger.entry_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RequestID(); ok {
		if err := linkcardledger.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "LinkCardLedger.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Reason(); ok {
		if err := linkcardledger.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "LinkCardLedger.reason": %w`, err)}
		}
	}
	return nil
}

func (_u *LinkCardLedgerUpdateOne) sqlSave(ctx context.Context) (_node *LinkCardLedger, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(linkcardledger.Table, linkcardledger.Columns, sqlgraph.NewFieldSpec(linkcardledger.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LinkCardLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, linkcardledger.FieldID)
		for _, f := range fields {
			if !linkcardledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != linkcardledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OperationID(); ok {
		_spec.SetField(linkcardledger.FieldOperationID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOperationID(); ok {
		_spec.AddField(linkcardledger.FieldOperationID, field.TypeInt64, value)
	}
	if _u.mutation.OperationIDCleared() {
		_spec.ClearField(linkcardledger.FieldOperationID, field.TypeInt64)
	}
	if value, ok := _u.mutation.APIKeyID(); ok {
		_spec.SetField(linkcardledger.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAPIKeyID(); ok {
		_spec.AddField(linkcardledger.FieldAPIKeyID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.CreatorUserID(); ok {
		_spec.SetField(linkcardledger.FieldCreatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatorUserID(); ok {
		_spec.AddField(linkcardledger.FieldCreatorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EntryType(); ok {
		_spec.SetField(linkcardledger.FieldEntryType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReserveDelta(); ok {
		_spec.SetField(linkcardledger.FieldReserveDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedReserveDelta(); ok {
		_spec.AddField(linkcardledger.FieldReserveDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CreatorBalanceDelta(); ok {
		_spec.SetField(linkcardledger.FieldCreatorBalanceDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCreatorBalanceDelta(); ok {
		_spec.AddField(linkcardledger.FieldCreatorBalanceDelta, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaBefore(); ok {
		_spec.SetField(linkcardledger.FieldQuotaBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaBefore(); ok {
		_spec.AddField(linkcardledger.FieldQuotaBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaAfter(); ok {
		_spec.SetField(linkcardledger.FieldQuotaAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaAfter(); ok {
		_spec.AddField(linkcardledger.FieldQuotaAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaUsedBefore(); ok {
		_spec.SetField(linkcardledger.FieldQuotaUsedBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsedBefore(); ok {
		_spec.AddField(linkcardledger.FieldQuotaUsedBefore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.QuotaUsedAfter(); ok {
		_spec.SetField(linkcardledger.FieldQuotaUsedAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedQuotaUsedAfter(); ok {
		_spec.AddField(linkcardledger.FieldQuotaUsedAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(linkcardledger.FieldRequestID, field.TypeString, value)
	}
	if _u.mutation.RequestIDCleared() {
		_spec.ClearField(linkcardledger.FieldRequestID, field.TypeString)
	}
	if value, ok := _u.mutation.ActorUserID(); ok {
		_spec.SetField(linkcardledger.FieldActorUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedActorUserID(); ok {
		_spec.AddField(linkcardledger.FieldActorUserID, field.TypeInt64, value)
	}
	if _u.mutation.ActorUserIDCleared() {
		_spec.ClearField(linkcardledger.FieldActorUserID, field.TypeInt64)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(linkcardledger.FieldReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(linkcardledger.FieldMetadata, field.TypeJSON, value)
	}
	if _u.mutation.MetadataCleared() {
		_spec.ClearField(linkcardledger.FieldMetadata, field.TypeJSON)
	}
	_node = &LinkCardLedger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{linkcardledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
