// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/linkcardledger"
)

// LinkCardLedgerCreate is the builder for creating a LinkCardLedger entity.
type LinkCardLedgerCreate struct {
	config
	mutation *LinkCardLedgerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetOperationID sets the "operation_id" field.
func (_c *LinkCardLedgerCreate) SetOperationID(v int64) *LinkCardLedgerCreate {
	_c.mutation.SetOperationID(v)
	return _c
}

// SetNillableOperationID sets the "operation_id" field if the given value is not nil.
func (_c *LinkCardLedgerCreate) SetNillableOperationID(v *int64) *LinkCardLedgerCreate {
	if v != nil {
		_c.SetOperationID(*v)
	}
	return _c
}

// SetAPIKeyID sets the "api_key_id" field.
func (_c *LinkCardLedgerCreate) SetAPIKeyID(v int64) *LinkCardLedgerCreate {
	_c.mutation.SetAPIKeyID(v)
	return _c
}

// SetCreatorUserID sets the "creator_user_id" field.
func (_c *LinkCardLedgerCreate) SetCreatorUserID(v int64) *LinkCardLedgerCreate {
	_c.mutation.SetCreatorUserID(v)
	return _c
}

// SetEntryType sets the "entry_type" field.
func (_c *LinkCardLedgerCreate) SetEntryType(v string) *LinkCardLedgerCreate {
	_c.mutation.SetEntryType(v)
	return _c
}

// SetReserveDelta sets the "reserve_delta" field.
func (_c *LinkCardLedgerCreate) SetReserveDelta(v float64) *LinkCardLedgerCreate {
	_c.mutation.SetReserveDelta(v)
	return _c
}

// SetCreatorBalanceDelta sets the "creator_balance_delta" field.
func (_c *LinkCardLedgerCreate) SetCreatorBalanceDelta(v float64) *LinkCardLedgerCreate {
	_c.mutation.SetCreatorBalanceDelta(v)
	return _c
}

// SetNillableCreatorBalanceDelta sets the "creator_balance_delta" field if the given value is not nil.
func (_c *LinkCardLedgerCreate) SetNillableCreatorBalanceDelta(v *float64) *LinkCardLedgerCreate {
	if v != nil {
		_c.SetCreatorBalanceDelta(*v)
	}
	return _c
}

// SetQuotaBefore sets the "quota_before" field.
func (_c *LinkCardLedgerCreate) SetQuotaBefore(v float64) *LinkCardLedgerCreate {
	_c.mutation.SetQuotaBefore(v)
	return _c
}

// SetQuotaAfter sets the "quota_after" field.
func (_c *LinkCardLedgerCreate) SetQuotaAfter(v float64) *LinkCardLedgerCreate {
	_c.mutation.SetQuotaAfter(v)
	return _c
}

// SetQuotaUsedBefore sets the "quota_used_before" field.
func (_c *LinkCardLedgerCreate) SetQuotaUsedBefore(v float64) *LinkCardLedgerCreate {
	_c.mutation.SetQuotaUsedBefore(v)
	return _c
}

// SetQuotaUsedAfter sets the "quota_used_after" field.
func (_c *LinkCardLedgerCreate) SetQuotaUsedAfter(v float64) *LinkCardLedgerCreate {
	_c.mutation.SetQuotaUsedAfter(v)
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *LinkCardLedgerCreate) SetRequestID(v string) *LinkCardLedgerCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *LinkCardLedgerCreate) SetNillableRequestID(v *string) *LinkCardLedgerCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetActorUserID sets the "actor_user_id" field.
func (_c *LinkCardLedgerCreate) SetActorUserID(v int64) *LinkCardLedgerCreate {
	_c.mutation.SetActorUserID(v)
	return _c
}

// SetNillableActorUserID sets the "actor_user_id" field if the given value is not nil.
func (_c *LinkCardLedgerCreate) SetNillableActorUserID(v *int64) *LinkCardLedgerCreate {
	if v != nil {
		_c.SetActorUserID(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *LinkCardLedgerCreate) SetReason(v string) *LinkCardLedgerCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_c *LinkCardLedgerCreate) SetNillableReason(v *string) *LinkCardLedgerCreate {
	if v != nil {
		_c.SetReason(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *LinkCardLedgerCreate) SetMetadata(v map[string]interface{}) *LinkCardLedgerCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *LinkCardLedgerCreate) SetCreatedAt(v time.Time) *LinkCardLedgerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *LinkCardLedgerCreate) SetNillableCreatedAt(v *time.Time) *LinkCardLedgerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the LinkCardLedgerMutation object of the builder.
func (_c *LinkCardLedgerCreate) Mutation() *LinkCardLedgerMutation {
	return _c.mutation
}

// Save creates the LinkCardLedger in the database.
func (_c *LinkCardLedgerCreate) Save(ctx context.Context) (*LinkCardLedger, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LinkCardLedgerCreate) SaveX(ctx context.Context) *LinkCardLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCardLedgerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCardLedgerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *LinkCardLedgerCreate) defaults() {
	if _, ok := _c.mutation.CreatorBalanceDelta(); !ok {
		v := linkcardledger.DefaultCreatorBalanceDelta
		_c.mutation.SetCreatorBalanceDelta(v)
	}
	if _, ok := _c.mutation.Reason(); !ok {
		v := linkcardledger.DefaultReason
		_c.mutation.SetReason(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := linkcardledger.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LinkCardLedgerCreate) check() error {
	if _, ok := _c.mutation.APIKeyID(); !ok {
		return &ValidationError{Name: "api_key_id", err: errors.New(`ent: missing required field "LinkCardLedger.api_key_id"`)}
	}
	if _, ok := _c.mutation.CreatorUserID(); !ok {
		return &ValidationError{Name: "creator_user_id", err: errors.New(`ent: missing required field "LinkCardLedger.creator_user_id"`)}
	}
	if _, ok := _c.mutation.EntryType(); !ok {
		return &ValidationError{Name: "entry_type", err: errors.New(`ent: missing required field "LinkCardLedger.entry_type"`)}
	}
	if v, ok := _c.mutation.EntryType(); ok {
		if err := linkcardledger.EntryTypeValidator(v); err != nil {
			return &ValidationError{Name: "entry_type", err: fmt.Errorf(`ent: validator failed for field "LinkCardLedger.entry_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ReserveDelta(); !ok {
		return &ValidationError{Name: "reserve_delta", err: errors.New(`ent: missing required field "LinkCardLedger.reserve_delta"`)}
	}
	if _, ok := _c.mutation.CreatorBalanceDelta(); !ok {
		return &ValidationError{Name: "creator_balance_delta", err: errors.New(`ent: missing required field "LinkCardLedger.creator_balance_delta"`)}
	}
	if _, ok := _c.mutation.QuotaBefore(); !ok {
		return &ValidationError{Name: "quota_before", err: errors.New(`ent: missing required field "LinkCardLedger.quota_before"`)}
	}
	if _, ok := _c.mutation.QuotaAfter(); !ok {
		return &ValidationError{Name: "quota_after", err: errors.New(`ent: missing required field "LinkCardLedger.quota_after"`)}
	}
	if _, ok := _c.mutation.QuotaUsedBefore(); !ok {
		return &ValidationError{Name: "quota_used_before", err: errors.New(`ent: missing required field "LinkCardLedger.quota_used_before"`)}
	}
	if _, ok := _c.mutation.QuotaUsedAfter(); !ok {
		return &ValidationError{Name: "quota_used_after", err: errors.New(`ent: missing required field "LinkCardLedger.quota_used_after"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := linkcardledger.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "LinkCardLedger.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "LinkCardLedger.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := linkcardledger.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "LinkCardLedger.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "LinkCardLedger.created_at"`)}
	}
	return nil
}

func (_c *LinkCardLedgerCreate) sqlSave(ctx context.Context) (*LinkCardLedger, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LinkCardLedgerCreate) createSpec() (*LinkCardLedger, *sqlgraph.CreateSpec) {
	var (
		_node = &LinkCardLedger{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(linkcardledger.Table, sqlgraph.NewFieldSpec(linkcardledger.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.OperationID(); ok {
		_spec.SetField(linkcardledger.FieldOperationID, field.TypeInt64, value)
		_node.OperationID = &value
	}
	if value, ok := _c.mutation.APIKeyID(); ok {
		_spec.SetField(linkcardledger.FieldAPIKeyID, field.TypeInt64, value)
		_node.APIKeyID = value
	}
	if value, ok := _c.mutation.CreatorUserID(); ok {
		_spec.SetField(linkcardledger.FieldCreatorUserID, field.TypeInt64, value)
		_node.CreatorUserID = value
	}
	if value, ok := _c.mutation.EntryType(); ok {
		_spec.SetField(linkcardledger.FieldEntryType, field.TypeString, value)
		_node.EntryType = value
	}
	if value, ok := _c.mutation.ReserveDelta(); ok {
		_spec.SetField(linkcardledger.FieldReserveDelta, field.TypeFloat64, value)
		_node.ReserveDelta = value
	}
	if value, ok := _c.mutation.CreatorBalanceDelta(); ok {
		_spec.SetField(linkcardledger.FieldCreatorBalanceDelta, field.TypeFloat64, value)
		_node.CreatorBalanceDelta = value
	}
	if value, ok := _c.mutation.QuotaBefore(); ok {
		_spec.SetField(linkcardledger.FieldQuotaBefore, field.TypeFloat64, value)
		_node.QuotaBefore = value
	}
	if value, ok := _c.mutation.QuotaAfter(); ok {
		_spec.SetField(linkcardledger.FieldQuotaAfter, field.TypeFloat64, value)
		_node.QuotaAfter = value
	}
	if value, ok := _c.mutation.QuotaUsedBefore(); ok {
		_spec.SetField(linkcardledger.FieldQuotaUsedBefore, field.TypeFloat64, value)
		_node.QuotaUsedBefore = value
	}
	if value, ok := _c.mutation.QuotaUsedAfter(); ok {
		_spec.SetField(linkcardledger.FieldQuotaUsedAfter, field.TypeFloat64, value)
		_node.QuotaUsedAfter = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(linkcardledger.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.ActorUserID(); ok {
		_spec.SetField(linkcardledger.FieldActorUserID, field.TypeInt64, value)
		_node.ActorUserID = &value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(linkcardledger.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(linkcardledger.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(linkcardledger.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LinkCardLedger.Create().
//		SetOperationID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LinkCardLedgerUpsert) {
//			SetOperationID(v+v).
//		}).
//		Exec(ctx)
func (_c *LinkCardLedgerCreate) OnConflict(opts ...sql.ConflictOption) *LinkCardLedgerUpsertOne {
	_c.conflict = opts
	return &LinkCardLedgerUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LinkCardLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LinkCardLedgerCreate) OnConflictColumns(columns ...string) *LinkCardLedgerUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LinkCardLedgerUpsertOne{
		create: _c,
	}
}

type (
	// LinkCardLedgerUpsertOne is the builder for "upsert"-ing
	//  one LinkCardLedger node.
	LinkCardLedgerUpsertOne struct {
		create *LinkCardLedgerCreate
	}

	// LinkCardLedgerUpsert is the "OnConflict" setter.
	LinkCardLedgerUpsert struct {
		*sql.UpdateSet
	}
)

// SetOperationID sets the "operation_id" field.
func (u *LinkCardLedgerUpsert) SetOperationID(v int64) *LinkCardLedgerUpsert {
	u.Set(linkcardledger.FieldOperationID, v)
	return u
}

// UpdateOperationID sets the "operation_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsert) UpdateOperationID() *LinkCardLedgerUpsert {
	u.SetExcluded(linkcardledger.FieldOperationID)
	return u
}

// AddOperationID adds v to the "operation_id" field.
func (u *LinkCardLedgerUpsert) AddOperationID(v int64) *LinkCardLedgerUpsert {
	u.Add(linkcardledger.FieldOperationID, v)
	return u
}

// ClearOperationID clears the value of the "operation_id" field.
func (u *LinkCardLedgerUpsert) ClearOperationID() *LinkCardLedgerUpsert {
	u.SetNull(linkcardledger.FieldOperationID)
	return u
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *LinkCardLedgerUpsert) SetAPIKeyID(v int64) *LinkCardLedgerUpsert {
	u.Set(linkcardledger.FieldAPIKeyID, v)
	return u
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsert) UpdateAPIKeyID() *LinkCardLedgerUpsert {
	u.SetExcluded(linkcardledger.FieldAPIKeyID)
	return u
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *LinkCardLedgerUpsert) AddAPIKeyID(v int64) *LinkCardLedgerUpsert {
	u.Add(linkcardledger.FieldAPIKeyID, v)
	return u
}

// SetCreatorUserID sets the "creator_user_id" field.
func (u *LinkCardLedgerUpsert) SetCreatorUserID(v int64) *LinkCardLedgerUpsert {
	u.Set(linkcardledger.FieldCreatorUserID, v)
	return u
}

// UpdateCreatorUserID sets the "creator_user_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsert) UpdateCreatorUserID() *LinkCardLedgerUpsert {
	u.SetExcluded(linkcardledger.FieldCreatorUserID)
	return u
}

// AddCreatorUserID adds v to the "creator_user_id" field.
func (u *LinkCardLedgerUpsert) AddCreatorUserID(v int64) *LinkCardLedgerUpsert {
	u.Add(linkcardledger.FieldCreatorUserID, v)
	return u
}

// SetEntryType sets the "entry_type" field.
func (u *LinkCardLedgerUpsert) SetEntryType(v string) *LinkCardLedgerUpsert {
	u.Set(linkcardledger.FieldEntryType, v)
	return u
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *LinkCardLedgerUpsert) UpdateEntryType() *LinkCardLedgerUpsert {
	u.SetExcluded(linkcardledger.FieldEntryType)
	return u
}

// SetReserveDelta sets the "reserve_delta" field.
func (u *LinkCardLedgerUpsert) SetReserveDelta(v float64) *LinkCardLedgerUpsert {
	u.Set(linkcardledger.FieldReserveDelta, v)
	return u
}

// UpdateReserveDelta sets the "reserve_delta" field to the value that was provided on create.
func (u *LinkCardLedgerUpsert) UpdateReserveDelta() *LinkCardLedgerUpsert {
	u.SetExcluded(linkcardledger.FieldReserveDelta)
	return u
}

// AddReserveDelta adds v to the "reserve_delta" field.
func (u *LinkCardLedgerUpsert) AddReserveDelta(v float64) *LinkCardLedgerUpsert {
	u.Add(linkcardledger.FieldReserveDelta, v)
	return u
}

// SetCreatorBalanceDelta sets the "creator_balance_delta" field.
func (u *LinkCardLedgerUpsert) SetCreatorBalanceDelta(v float64) *LinkCardLedgerUpsert {
	u.Set(linkcardledger.FieldCreatorBalanceDelta, v)
	return u
}

// UpdateCreatorBalanceDelta sets the "creator_balance_delta" field to the value that was provided on create.
func (u *LinkCardLedgerUpsert) UpdateCreatorBalanceDelta() *LinkCardLedgerUpsert {
	u.SetExcluded(linkcardledger.FieldCreatorBalanceDelta)
	return u
}

// AddCreatorBalanceDelta adds v to the "creator_balance_delta" field.
func (u *LinkCardLedgerUpsert) AddCreatorBalanceDelta(v float64) *LinkCardLedgerUpsert {
	u.Add(linkcardledger.FieldCreatorBalanceDelta, v)
	return u
}

// SetQuotaBefore sets the "quota_before" field.
func (u *LinkCardLedgerUpsert) SetQuotaBefore(v float64) *LinkCardLedgerUpsert {
	u.Set(linkcardledger.FieldQuotaBefore, v)
	return u
}

// UpdateQuotaBefore sets the "quota_before" field to the value that was provided on create.
func (u *LinkCardLedgerUpsert) UpdateQuotaBefore() *LinkCardLedgerUpsert {
	u.SetExcluded(linkcardledger.FieldQuotaBefore)
	return u
}

// AddQuotaBefore adds v to the "quota_before" field.
func (u *LinkCardLedgerUpsert) AddQuotaBefore(v float64) *LinkCardLedgerUpsert {
	u.Add(linkcardledger.FieldQuotaBefore, v)
	return u
}

// SetQuotaAfter sets the "quota_after" field.
func (u *LinkCardLedgerUpsert) SetQuotaAfter(v float64) *LinkCardLedgerUpsert {
	u.Set(linkcardledger.FieldQuotaAfter, v)
	return u
}

// UpdateQuotaAfter sets the "quota_after" field to the value that was provided on create.
func (u *LinkCardLedgerUpsert) UpdateQuotaAfter() *LinkCardLedgerUpsert {
	u.SetExcluded(linkcardledger.FieldQuotaAfter)
	return u
}

// AddQuotaAfter adds v to the "quota_after" field.
func (u *LinkCardLedgerUpsert) AddQuotaAfter(v float64) *LinkCardLedgerUpsert {
	u.Add(linkcardledger.FieldQuotaAfter, v)
	return u
}

// SetQuotaUsedBefore sets the "quota_used_before" field.
func (u *LinkCardLedgerUpsert) SetQuotaUsedBefore(v float64) *LinkCardLedgerUpsert {
	u.Set(linkcardledger.FieldQuotaUsedBefore, v)
	return u
}

// UpdateQuotaUsedBefore sets the "quota_used_before" field to the value that was provided on create.
func (u *LinkCardLedgerUpsert) UpdateQuotaUsedBefore() *LinkCardLedgerUpsert {
	u.SetExcluded(linkcardledger.FieldQuotaUsedBefore)
	return u
}

// AddQuotaUsedBefore adds v to the "quota_used_before" field.
func (u *LinkCardLedgerUpsert) AddQuotaUsedBefore(v float64) *LinkCardLedgerUpsert {
	u.Add(linkcardledger.FieldQuotaUsedBefore, v)
	return u
}

// SetQuotaUsedAfter sets the "quota_used_after" field.
func (u *LinkCardLedgerUpsert) SetQuotaUsedAfter(v float64) *LinkCardLedgerUpsert {
	u.Set(linkcardledger.FieldQuotaUsedAfter, v)
	return u
}

// UpdateQuotaUsedAfter sets the "quota_used_after" field to the value that was provided on create.
func (u *LinkCardLedgerUpsert) UpdateQuotaUsedAfter() *LinkCardLedgerUpsert {
	u.SetExcluded(linkcardledger.FieldQuotaUsedAfter)
	return u
}

// AddQuotaUsedAfter adds v to the "quota_used_after" field.
func (u *LinkCardLedgerUpsert) AddQuotaUsedAfter(v float64) *LinkCardLedgerUpsert {
	u.Add(linkcardledger.FieldQuotaUsedAfter, v)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *LinkCardLedgerUpsert) SetRequestID(v string) *LinkCardLedgerUpsert {
	u.Set(linkcardledger.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsert) UpdateRequestID() *LinkCardLedgerUpsert {
	u.SetExcluded(linkcardledger.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *LinkCardLedgerUpsert) ClearRequestID() *LinkCardLedgerUpsert {
	u.SetNull(linkcardledger.FieldRequestID)
	return u
}

// SetActorUserID sets the "actor_user_id" field.
func (u *LinkCardLedgerUpsert) SetActorUserID(v int64) *LinkCardLedgerUpsert {
	u.Set(linkcardledger.FieldActorUserID, v)
	return u
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsert) UpdateActorUserID() *LinkCardLedgerUpsert {
	u.SetExcluded(linkcardledger.FieldActorUserID)
	return u
}

// AddActorUserID adds v to the "actor_user_id" field.
func (u *LinkCardLedgerUpsert) AddActorUserID(v int64) *LinkCardLedgerUpsert {
	u.Add(linkcardledger.FieldActorUserID, v)
	return u
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (u *LinkCardLedgerUpsert) ClearActorUserID() *LinkCardLedgerUpsert {
	u.SetNull(linkcardledger.FieldActorUserID)
	return u
}

// SetReason sets the "reason" field.
func (u *LinkCardLedgerUpsert) SetReason(v string) *LinkCardLedgerUpsert {
	u.Set(linkcardledger.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *LinkCardLedgerUpsert) UpdateReason() *LinkCardLedgerUpsert {
	u.SetExcluded(linkcardledger.FieldReason)
	return u
}

// SetMetadata sets the "metadata" field.
func (u *LinkCardLedgerUpsert) SetMetadata(v map[string]interface{}) *LinkCardLedgerUpsert {
	u.Set(linkcardledger.FieldMetadata, v)
	return u
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *LinkCardLedgerUpsert) UpdateMetadata() *LinkCardLedgerUpsert {
	u.SetExcluded(linkcardledger.FieldMetadata)
	return u
}

// ClearMetadata clears the value of the "metadata" field.
func (u *LinkCardLedgerUpsert) ClearMetadata() *LinkCardLedgerUpsert {
	u.SetNull(linkcardledger.FieldMetadata)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.LinkCardLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LinkCardLedgerUpsertOne) UpdateNewValues() *LinkCardLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(linkcardledger.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LinkCardLedger.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *LinkCardLedgerUpsertOne) Ignore() *LinkCardLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LinkCardLedgerUpsertOne) DoNothing() *LinkCardLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LinkCardLedgerCreate.OnConflict
// documentation for more info.
func (u *LinkCardLedgerUpsertOne) Update(set func(*LinkCardLedgerUpsert)) *LinkCardLedgerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LinkCardLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetOperationID sets the "operation_id" field.
func (u *LinkCardLedgerUpsertOne) SetOperationID(v int64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetOperationID(v)
	})
}

// AddOperationID adds v to the "operation_id" field.
func (u *LinkCardLedgerUpsertOne) AddOperationID(v int64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddOperationID(v)
	})
}

// UpdateOperationID sets the "operation_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertOne) UpdateOperationID() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateOperationID()
	})
}

// ClearOperationID clears the value of the "operation_id" field.
func (u *LinkCardLedgerUpsertOne) ClearOperationID() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.ClearOperationID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *LinkCardLedgerUpsertOne) SetAPIKeyID(v int64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *LinkCardLedgerUpsertOne) AddAPIKeyID(v int64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertOne) UpdateAPIKeyID() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetCreatorUserID sets the "creator_user_id" field.
func (u *LinkCardLedgerUpsertOne) SetCreatorUserID(v int64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetCreatorUserID(v)
	})
}

// AddCreatorUserID adds v to the "creator_user_id" field.
func (u *LinkCardLedgerUpsertOne) AddCreatorUserID(v int64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddCreatorUserID(v)
	})
}

// UpdateCreatorUserID sets the "creator_user_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertOne) UpdateCreatorUserID() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateCreatorUserID()
	})
}

// SetEntryType sets the "entry_type" field.
func (u *LinkCardLedgerUpsertOne) SetEntryType(v string) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetEntryType(v)
	})
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertOne) UpdateEntryType() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateEntryType()
	})
}

// SetReserveDelta sets the "reserve_delta" field.
func (u *LinkCardLedgerUpsertOne) SetReserveDelta(v float64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetReserveDelta(v)
	})
}

// AddReserveDelta adds v to the "reserve_delta" field.
func (u *LinkCardLedgerUpsertOne) AddReserveDelta(v float64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddReserveDelta(v)
	})
}

// UpdateReserveDelta sets the "reserve_delta" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertOne) UpdateReserveDelta() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateReserveDelta()
	})
}

// SetCreatorBalanceDelta sets the "creator_balance_delta" field.
func (u *LinkCardLedgerUpsertOne) SetCreatorBalanceDelta(v float64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetCreatorBalanceDelta(v)
	})
}

// AddCreatorBalanceDelta adds v to the "creator_balance_delta" field.
func (u *LinkCardLedgerUpsertOne) AddCreatorBalanceDelta(v float64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddCreatorBalanceDelta(v)
	})
}

// UpdateCreatorBalanceDelta sets the "creator_balance_delta" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertOne) UpdateCreatorBalanceDelta() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateCreatorBalanceDelta()
	})
}

// SetQuotaBefore sets the "quota_before" field.
func (u *LinkCardLedgerUpsertOne) SetQuotaBefore(v float64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetQuotaBefore(v)
	})
}

// AddQuotaBefore adds v to the "quota_before" field.
func (u *LinkCardLedgerUpsertOne) AddQuotaBefore(v float64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddQuotaBefore(v)
	})
}

// UpdateQuotaBefore sets the "quota_before" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertOne) UpdateQuotaBefore() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateQuotaBefore()
	})
}

// SetQuotaAfter sets the "quota_after" field.
func (u *LinkCardLedgerUpsertOne) SetQuotaAfter(v float64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetQuotaAfter(v)
	})
}

// AddQuotaAfter adds v to the "quota_after" field.
func (u *LinkCardLedgerUpsertOne) AddQuotaAfter(v float64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddQuotaAfter(v)
	})
}

// UpdateQuotaAfter sets the "quota_after" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertOne) UpdateQuotaAfter() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateQuotaAfter()
	})
}

// SetQuotaUsedBefore sets the "quota_used_before" field.
func (u *LinkCardLedgerUpsertOne) SetQuotaUsedBefore(v float64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetQuotaUsedBefore(v)
	})
}

// AddQuotaUsedBefore adds v to the "quota_used_before" field.
func (u *LinkCardLedgerUpsertOne) AddQuotaUsedBefore(v float64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddQuotaUsedBefore(v)
	})
}

// UpdateQuotaUsedBefore sets the "quota_used_before" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertOne) UpdateQuotaUsedBefore() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateQuotaUsedBefore()
	})
}

// SetQuotaUsedAfter sets the "quota_used_after" field.
func (u *LinkCardLedgerUpsertOne) SetQuotaUsedAfter(v float64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetQuotaUsedAfter(v)
	})
}

// AddQuotaUsedAfter adds v to the "quota_used_after" field.
func (u *LinkCardLedgerUpsertOne) AddQuotaUsedAfter(v float64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddQuotaUsedAfter(v)
	})
}

// UpdateQuotaUsedAfter sets the "quota_used_after" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertOne) UpdateQuotaUsedAfter() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateQuotaUsedAfter()
	})
}

// SetRequestID sets the "request_id" field.
func (u *LinkCardLedgerUpsertOne) SetRequestID(v string) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertOne) UpdateRequestID() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *LinkCardLedgerUpsertOne) ClearRequestID() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.ClearRequestID()
	})
}

// SetActorUserID sets the "actor_user_id" field.
func (u *LinkCardLedgerUpsertOne) SetActorUserID(v int64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetActorUserID(v)
	})
}

// AddActorUserID adds v to the "actor_user_id" field.
func (u *LinkCardLedgerUpsertOne) AddActorUserID(v int64) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddActorUserID(v)
	})
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertOne) UpdateActorUserID() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateActorUserID()
	})
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (u *LinkCardLedgerUpsertOne) ClearActorUserID() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.ClearActorUserID()
	})
}

// SetReason sets the "reason" field.
func (u *LinkCardLedgerUpsertOne) SetReason(v string) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertOne) UpdateReason() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateReason()
	})
}

// SetMetadata sets the "metadata" field.
func (u *LinkCardLedgerUpsertOne) SetMetadata(v map[string]interface{}) *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertOne) UpdateMetadata() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *LinkCardLedgerUpsertOne) ClearMetadata() *LinkCardLedgerUpsertOne {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *LinkCardLedgerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LinkCardLedgerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LinkCardLedgerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *LinkCardLedgerUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *LinkCardLedgerUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// LinkCardLedgerCreateBulk is the builder for creating many LinkCardLedger entities in bulk.
type LinkCardLedgerCreateBulk struct {
	config
	err      error
	builders []*LinkCardLedgerCreate
	conflict []sql.ConflictOption
}

// Save creates the LinkCardLedger entities in the database.
func (_c *LinkCardLedgerCreateBulk) Save(ctx context.Context) ([]*LinkCardLedger, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*LinkCardLedger, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LinkCardLedgerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LinkCardLedgerCreateBulk) SaveX(ctx context.Context) []*LinkCardLedger {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LinkCardLedgerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LinkCardLedgerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.LinkCardLedger.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.LinkCardLedgerUpsert) {
//			SetOperationID(v+v).
//		}).
//		Exec(ctx)
func (_c *LinkCardLedgerCreateBulk) OnConflict(opts ...sql.ConflictOption) *LinkCardLedgerUpsertBulk {
	_c.conflict = opts
	return &LinkCardLedgerUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.LinkCardLedger.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *LinkCardLedgerCreateBulk) OnConflictColumns(columns ...string) *LinkCardLedgerUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &LinkCardLedgerUpsertBulk{
		create: _c,
	}
}

// LinkCardLedgerUpsertBulk is the builder for "upsert"-ing
// a bulk of LinkCardLedger nodes.
type LinkCardLedgerUpsertBulk struct {
	create *LinkCardLedgerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.LinkCardLedger.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *LinkCardLedgerUpsertBulk) UpdateNewValues() *LinkCardLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(linkcardledger.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.LinkCardLedger.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *LinkCardLedgerUpsertBulk) Ignore() *LinkCardLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *LinkCardLedgerUpsertBulk) DoNothing() *LinkCardLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the LinkCardLedgerCreateBulk.OnConflict
// documentation for more info.
func (u *LinkCardLedgerUpsertBulk) Update(set func(*LinkCardLedgerUpsert)) *LinkCardLedgerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&LinkCardLedgerUpsert{UpdateSet: update})
	}))
	return u
}

// SetOperationID sets the "operation_id" field.
func (u *LinkCardLedgerUpsertBulk) SetOperationID(v int64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetOperationID(v)
	})
}

// AddOperationID adds v to the "operation_id" field.
func (u *LinkCardLedgerUpsertBulk) AddOperationID(v int64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddOperationID(v)
	})
}

// UpdateOperationID sets the "operation_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertBulk) UpdateOperationID() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateOperationID()
	})
}

// ClearOperationID clears the value of the "operation_id" field.
func (u *LinkCardLedgerUpsertBulk) ClearOperationID() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.ClearOperationID()
	})
}

// SetAPIKeyID sets the "api_key_id" field.
func (u *LinkCardLedgerUpsertBulk) SetAPIKeyID(v int64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetAPIKeyID(v)
	})
}

// AddAPIKeyID adds v to the "api_key_id" field.
func (u *LinkCardLedgerUpsertBulk) AddAPIKeyID(v int64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddAPIKeyID(v)
	})
}

// UpdateAPIKeyID sets the "api_key_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertBulk) UpdateAPIKeyID() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateAPIKeyID()
	})
}

// SetCreatorUserID sets the "creator_user_id" field.
func (u *LinkCardLedgerUpsertBulk) SetCreatorUserID(v int64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetCreatorUserID(v)
	})
}

// AddCreatorUserID adds v to the "creator_user_id" field.
func (u *LinkCardLedgerUpsertBulk) AddCreatorUserID(v int64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddCreatorUserID(v)
	})
}

// UpdateCreatorUserID sets the "creator_user_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertBulk) UpdateCreatorUserID() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateCreatorUserID()
	})
}

// SetEntryType sets the "entry_type" field.
func (u *LinkCardLedgerUpsertBulk) SetEntryType(v string) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetEntryType(v)
	})
}

// UpdateEntryType sets the "entry_type" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertBulk) UpdateEntryType() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateEntryType()
	})
}

// SetReserveDelta sets the "reserve_delta" field.
func (u *LinkCardLedgerUpsertBulk) SetReserveDelta(v float64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetReserveDelta(v)
	})
}

// AddReserveDelta adds v to the "reserve_delta" field.
func (u *LinkCardLedgerUpsertBulk) AddReserveDelta(v float64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddReserveDelta(v)
	})
}

// UpdateReserveDelta sets the "reserve_delta" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertBulk) UpdateReserveDelta() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateReserveDelta()
	})
}

// SetCreatorBalanceDelta sets the "creator_balance_delta" field.
func (u *LinkCardLedgerUpsertBulk) SetCreatorBalanceDelta(v float64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetCreatorBalanceDelta(v)
	})
}

// AddCreatorBalanceDelta adds v to the "creator_balance_delta" field.
func (u *LinkCardLedgerUpsertBulk) AddCreatorBalanceDelta(v float64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddCreatorBalanceDelta(v)
	})
}

// UpdateCreatorBalanceDelta sets the "creator_balance_delta" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertBulk) UpdateCreatorBalanceDelta() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateCreatorBalanceDelta()
	})
}

// SetQuotaBefore sets the "quota_before" field.
func (u *LinkCardLedgerUpsertBulk) SetQuotaBefore(v float64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetQuotaBefore(v)
	})
}

// AddQuotaBefore adds v to the "quota_before" field.
func (u *LinkCardLedgerUpsertBulk) AddQuotaBefore(v float64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddQuotaBefore(v)
	})
}

// UpdateQuotaBefore sets the "quota_before" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertBulk) UpdateQuotaBefore() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateQuotaBefore()
	})
}

// SetQuotaAfter sets the "quota_after" field.
func (u *LinkCardLedgerUpsertBulk) SetQuotaAfter(v float64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetQuotaAfter(v)
	})
}

// AddQuotaAfter adds v to the "quota_after" field.
func (u *LinkCardLedgerUpsertBulk) AddQuotaAfter(v float64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddQuotaAfter(v)
	})
}

// UpdateQuotaAfter sets the "quota_after" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertBulk) UpdateQuotaAfter() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateQuotaAfter()
	})
}

// SetQuotaUsedBefore sets the "quota_used_before" field.
func (u *LinkCardLedgerUpsertBulk) SetQuotaUsedBefore(v float64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetQuotaUsedBefore(v)
	})
}

// AddQuotaUsedBefore adds v to the "quota_used_before" field.
func (u *LinkCardLedgerUpsertBulk) AddQuotaUsedBefore(v float64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddQuotaUsedBefore(v)
	})
}

// UpdateQuotaUsedBefore sets the "quota_used_before" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertBulk) UpdateQuotaUsedBefore() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateQuotaUsedBefore()
	})
}

// SetQuotaUsedAfter sets the "quota_used_after" field.
func (u *LinkCardLedgerUpsertBulk) SetQuotaUsedAfter(v float64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetQuotaUsedAfter(v)
	})
}

// AddQuotaUsedAfter adds v to the "quota_used_after" field.
func (u *LinkCardLedgerUpsertBulk) AddQuotaUsedAfter(v float64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddQuotaUsedAfter(v)
	})
}

// UpdateQuotaUsedAfter sets the "quota_used_after" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertBulk) UpdateQuotaUsedAfter() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateQuotaUsedAfter()
	})
}

// SetRequestID sets the "request_id" field.
func (u *LinkCardLedgerUpsertBulk) SetRequestID(v string) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertBulk) UpdateRequestID() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *LinkCardLedgerUpsertBulk) ClearRequestID() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.ClearRequestID()
	})
}

// SetActorUserID sets the "actor_user_id" field.
func (u *LinkCardLedgerUpsertBulk) SetActorUserID(v int64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetActorUserID(v)
	})
}

// AddActorUserID adds v to the "actor_user_id" field.
func (u *LinkCardLedgerUpsertBulk) AddActorUserID(v int64) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.AddActorUserID(v)
	})
}

// UpdateActorUserID sets the "actor_user_id" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertBulk) UpdateActorUserID() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateActorUserID()
	})
}

// ClearActorUserID clears the value of the "actor_user_id" field.
func (u *LinkCardLedgerUpsertBulk) ClearActorUserID() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.ClearActorUserID()
	})
}

// SetReason sets the "reason" field.
func (u *LinkCardLedgerUpsertBulk) SetReason(v string) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertBulk) UpdateReason() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateReason()
	})
}

// SetMetadata sets the "metadata" field.
func (u *LinkCardLedgerUpsertBulk) SetMetadata(v map[string]interface{}) *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.SetMetadata(v)
	})
}

// UpdateMetadata sets the "metadata" field to the value that was provided on create.
func (u *LinkCardLedgerUpsertBulk) UpdateMetadata() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.UpdateMetadata()
	})
}

// ClearMetadata clears the value of the "metadata" field.
func (u *LinkCardLedgerUpsertBulk) ClearMetadata() *LinkCardLedgerUpsertBulk {
	return u.Update(func(s *LinkCardLedgerUpsert) {
		s.ClearMetadata()
	})
}

// Exec executes the query.
func (u *LinkCardLedgerUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the LinkCardLedgerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for LinkCardLedgerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *LinkCardLedgerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
