// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/linkcardgroupauthorization"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LinkCardGroupAuthorizationDelete is the builder for deleting a LinkCardGroupAuthorization entity.
type LinkCardGroupAuthorizationDelete struct {
	config
	hooks    []Hook
	mutation *LinkCardGroupAuthorizationMutation
}

// Where appends a list predicates to the LinkCardGroupAuthorizationDelete builder.
func (_d *LinkCardGroupAuthorizationDelete) Where(ps ...predicate.LinkCardGroupAuthorization) *LinkCardGroupAuthorizationDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *LinkCardGroupAuthorizationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LinkCardGroupAuthorizationDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *LinkCardGroupAuthorizationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(linkcardgroupauthorization.Table, sqlgraph.NewFieldSpec(linkcardgroupauthorization.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// LinkCardGroupAuthorizationDeleteOne is the builder for deleting a single LinkCardGroupAuthorization entity.
type LinkCardGroupAuthorizationDeleteOne struct {
	_d *LinkCardGroupAuthorizationDelete
}

// Where appends a list predicates to the LinkCardGroupAuthorizationDelete builder.
func (_d *LinkCardGroupAuthorizationDeleteOne) Where(ps ...predicate.LinkCardGroupAuthorization) *LinkCardGroupAuthorizationDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *LinkCardGroupAuthorizationDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{linkcardgroupauthorization.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *LinkCardGroupAuthorizationDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
