// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/linkcardgroupauthorization"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// LinkCardGroupAuthorizationUpdate is the builder for updating LinkCardGroupAuthorization entities.
type LinkCardGroupAuthorizationUpdate struct {
	config
	hooks    []Hook
	mutation *LinkCardGroupAuthorizationMutation
}

// Where appends a list predicates to the LinkCardGroupAuthorizationUpdate builder.
func (_u *LinkCardGroupAuthorizationUpdate) Where(ps ...predicate.LinkCardGroupAuthorization) *LinkCardGroupAuthorizationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *LinkCardGroupAuthorizationUpdate) SetGroupID(v int64) *LinkCardGroupAuthorizationUpdate {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *LinkCardGroupAuthorizationUpdate) SetNillableGroupID(v *int64) *LinkCardGroupAuthorizationUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *LinkCardGroupAuthorizationUpdate) AddGroupID(v int64) *LinkCardGroupAuthorizationUpdate {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *LinkCardGroupAuthorizationUpdate) SetEnabled(v bool) *LinkCardGroupAuthorizationUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *LinkCardGroupAuthorizationUpdate) SetNillableEnabled(v *bool) *LinkCardGroupAuthorizationUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *LinkCardGroupAuthorizationUpdate) SetSortOrder(v int) *LinkCardGroupAuthorizationUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *LinkCardGroupAuthorizationUpdate) SetNillableSortOrder(v *int) *LinkCardGroupAuthorizationUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *LinkCardGroupAuthorizationUpdate) AddSortOrder(v int) *LinkCardGroupAuthorizationUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *LinkCardGroupAuthorizationUpdate) SetCreatedBy(v int64) *LinkCardGroupAuthorizationUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *LinkCardGroupAuthorizationUpdate) SetNillableCreatedBy(v *int64) *LinkCardGroupAuthorizationUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *LinkCardGroupAuthorizationUpdate) AddCreatedBy(v int64) *LinkCardGroupAuthorizationUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *LinkCardGroupAuthorizationUpdate) ClearCreatedBy() *LinkCardGroupAuthorizationUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LinkCardGroupAuthorizationUpdate) SetUpdatedAt(v time.Time) *LinkCardGroupAuthorizationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the LinkCardGroupAuthorizationMutation object of the builder.
func (_u *LinkCardGroupAuthorizationUpdate) Mutation() *LinkCardGroupAuthorizationMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LinkCardGroupAuthorizationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkCardGroupAuthorizationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LinkCardGroupAuthorizationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkCardGroupAuthorizationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LinkCardGroupAuthorizationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := linkcardgroupauthorization.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *LinkCardGroupAuthorizationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(linkcardgroupauthorization.Table, linkcardgroupauthorization.Columns, sqlgraph.NewFieldSpec(linkcardgroupauthorization.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(linkcardgroupauthorization.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(linkcardgroupauthorization.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(linkcardgroupauthorization.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(linkcardgroupauthorization.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{linkcardgroupauthorization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LinkCardGroupAuthorizationUpdateOne is the builder for updating a single LinkCardGroupAuthorization entity.
type LinkCardGroupAuthorizationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LinkCardGroupAuthorizationMutation
}

// SetGroupID sets the "group_id" field.
func (_u *LinkCardGroupAuthorizationUpdateOne) SetGroupID(v int64) *LinkCardGroupAuthorizationUpdateOne {
	_u.mutation.ResetGroupID()
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *LinkCardGroupAuthorizationUpdateOne) SetNillableGroupID(v *int64) *LinkCardGroupAuthorizationUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// AddGroupID adds value to the "group_id" field.
func (_u *LinkCardGroupAuthorizationUpdateOne) AddGroupID(v int64) *LinkCardGroupAuthorizationUpdateOne {
	_u.mutation.AddGroupID(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *LinkCardGroupAuthorizationUpdateOne) SetEnabled(v bool) *LinkCardGroupAuthorizationUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *LinkCardGroupAuthorizationUpdateOne) SetNillableEnabled(v *bool) *LinkCardGroupAuthorizationUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *LinkCardGroupAuthorizationUpdateOne) SetSortOrder(v int) *LinkCardGroupAuthorizationUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *LinkCardGroupAuthorizationUpdateOne) SetNillableSortOrder(v *int) *LinkCardGroupAuthorizationUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *LinkCardGroupAuthorizationUpdateOne) AddSortOrder(v int) *LinkCardGroupAuthorizationUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *LinkCardGroupAuthorizationUpdateOne) SetCreatedBy(v int64) *LinkCardGroupAuthorizationUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *LinkCardGroupAuthorizationUpdateOne) SetNillableCreatedBy(v *int64) *LinkCardGroupAuthorizationUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *LinkCardGroupAuthorizationUpdateOne) AddCreatedBy(v int64) *LinkCardGroupAuthorizationUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *LinkCardGroupAuthorizationUpdateOne) ClearCreatedBy() *LinkCardGroupAuthorizationUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LinkCardGroupAuthorizationUpdateOne) SetUpdatedAt(v time.Time) *LinkCardGroupAuthorizationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the LinkCardGroupAuthorizationMutation object of the builder.
func (_u *LinkCardGroupAuthorizationUpdateOne) Mutation() *LinkCardGroupAuthorizationMutation {
	return _u.mutation
}

// Where appends a list predicates to the LinkCardGroupAuthorizationUpdate builder.
func (_u *LinkCardGroupAuthorizationUpdateOne) Where(ps ...predicate.LinkCardGroupAuthorization) *LinkCardGroupAuthorizationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LinkCardGroupAuthorizationUpdateOne) Select(field string, fields ...string) *LinkCardGroupAuthorizationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LinkCardGroupAuthorization entity.
func (_u *LinkCardGroupAuthorizationUpdateOne) Save(ctx context.Context) (*LinkCardGroupAuthorization, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LinkCardGroupAuthorizationUpdateOne) SaveX(ctx context.Context) *LinkCardGroupAuthorization {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LinkCardGroupAuthorizationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LinkCardGroupAuthorizationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *LinkCardGroupAuthorizationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := linkcardgroupauthorization.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *LinkCardGroupAuthorizationUpdateOne) sqlSave(ctx context.Context) (_node *LinkCardGroupAuthorization, err error) {
	_spec := sqlgraph.NewUpdateSpec(linkcardgroupauthorization.Table, linkcardgroupauthorization.Columns, sqlgraph.NewFieldSpec(linkcardgroupauthorization.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LinkCardGroupAuthorization.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, linkcardgroupauthorization.FieldID)
		for _, f := range fields {
			if !linkcardgroupauthorization.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != linkcardgroupauthorization.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.GroupID(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedGroupID(); ok {
		_spec.AddField(linkcardgroupauthorization.FieldGroupID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(linkcardgroupauthorization.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldCreatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(linkcardgroupauthorization.FieldCreatedBy, field.TypeInt64, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(linkcardgroupauthorization.FieldCreatedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(linkcardgroupauthorization.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &LinkCardGroupAuthorization{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{linkcardgroupauthorization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
