export default {
  linkCards: {
    title: 'Link Card Center', subtitle: 'Create prepaid API cards with an immutable billing group',
    adminTitle: 'Link Card Console', adminSubtitle: 'Manage availability, authorized groups, cards, and requests',
    cardPortal: 'Quota Card Center', create: 'Create cards', myCards: 'My cards', usage: 'Usage', overview: 'Overview', groups: 'Authorized groups', cards: 'Card operations',
    balance: 'Account balance', deposit: 'Deposit per card', quantity: 'Quantity', totalDebit: 'Total debit', baseQuota: 'Base quota', selectGroup: 'Select an authorized group', groupRate: '{rate}x group', concurrency: 'Concurrency {value}',
    createAction: 'Debit and create', creating: 'Creating', createSuccess: 'Cards created', createFailed: 'Creation failed. Check the balance and parameters.', insufficientBalance: 'Insufficient balance. No card will be created.',
    fullKey: 'Full Key', cardKey: 'Link Key', searchKey: 'Search full Key', allStatus: 'All statuses', pending: 'Pending activation', active: 'Active', frozen: 'Frozen', exhausted: 'Payment due', revoked: 'Revoked',
    initialQuota: 'Initial quota', remainingQuota: 'Remaining quota', usedQuota: 'Used', owner: 'Creator', status: 'Status', createdAt: 'Created', actions: 'Actions',
    copy: 'Copy', copied: 'Key copied', copyFullKey: 'Copy the full Link Key', keyCopied: 'Full Link Key copied', recharge: 'Recharge', refund: 'Refund and revoke', rechargeAmount: 'Recharge amount', rechargeSuccess: 'Recharge complete', rechargeFailed: 'Recharge failed',
    refundTitle: 'Confirm refund', refundMessage: 'Only an inactive, unused card without an in-flight request can be refunded. The Key is revoked immediately.', refundSuccess: 'Balance refunded and Key revoked', refundFailed: 'Refund failed because the card state may have changed.',
    noCards: 'No cards', noGroups: 'No groups have been authorized', noUsage: 'No requests', accessDenied: 'Link Card Center is not available', retry: 'Retry',
    featureSwitch: 'Enable Link Cards', featureHint: 'When disabled, user menu and routes are hidden. Gateway behavior for issued cards remains server-controlled.', previewOnly: 'Development rollout', previewHint: 'Only the server-side development list can access and create cards before launch.', developmentUsers: 'Development user IDs', developmentUsersPlaceholder: '1, 2, 3', developmentUsersHint: 'Comma-separated positive user IDs. Keep only ID 1 during the current validation phase.', defaultConcurrency: 'Default concurrency', defaultRPM: 'Default RPM (0 = unlimited)', batchLimit: 'Maximum cards per batch', minimumDeposit: 'Minimum deposit per card', noMinimumDeposit: 'No minimum', sessionTTL: 'Public session lifetime (seconds)', publicPortalURL: 'Quota Card Center URL', apiBaseURL: 'API Base URL', saveSettings: 'Save settings', settingsSaved: 'Settings saved', settingsFailed: 'Failed to save settings',
    totalCards: 'Total cards', activeCards: 'Active cards', totalReserved: 'Total reserved', totalConsumed: 'Total consumed', authorizeGroup: 'Authorize group', removeAuthorization: 'Remove', groupAuthorized: 'Group authorized', groupRemoved: 'Authorization removed',
    adminAction: 'Card action', freeze: 'Freeze', unfreeze: 'Unfreeze', destroy: 'Revoke', adminRefund: 'Refund remainder', limit: 'Set limits', audit: 'View audit', actionReason: 'Reason', actionAmount: 'Amount', actionSuccess: 'Action complete', actionFailed: 'Action failed',
    requestId: 'Request ID', model: 'Model', tokens: 'Token details', cost: 'Cost details', requestType: 'Type', latency: 'TTFT / duration',
    activateTitle: 'Enter a Key to activate', activateSubtitle: 'Enter the complete quota-card Key. After validation, balance and usage become available.', keyPlaceholder: 'sk-card-...', activate: 'Validate and activate', activating: 'Validating', invalidKey: 'Enter a complete valid quota-card Key', activationFailed: 'The Key is invalid, revoked, or unavailable', sessionExpired: 'The session expired. Enter the Key again.', clearSession: 'Query another Key', availableBalance: 'Available quota', cardStatus: 'Card status', requestCount: 'Requests', integration: 'Integration guide', codex: 'Codex', claude: 'Claude', openaiCompatible: 'OpenAI compatible', streamRequired: 'All examples use streaming output', endpoint: 'API endpoint', copyEndpoint: 'Copy API endpoint', endpointCopied: 'API endpoint copied', guideCopied: 'Integration example copied', loading: 'Loading quota-card data',
  },
}
