// Code generated by ent, DO NOT EDIT.

package linkcardoperation

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLTE(FieldID, id))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldScope, v))
}

// ActorUserID applies equality check predicate on the "actor_user_id" field. It's identical to ActorUserIDEQ.
func ActorUserID(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldActorUserID, v))
}

// CreatorUserID applies equality check predicate on the "creator_user_id" field. It's identical to CreatorUserIDEQ.
func CreatorUserID(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldCreatorUserID, v))
}

// APIKeyID applies equality check predicate on the "api_key_id" field. It's identical to APIKeyIDEQ.
func APIKeyID(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldAPIKeyID, v))
}

// IdempotencyKeyHash applies equality check predicate on the "idempotency_key_hash" field. It's identical to IdempotencyKeyHashEQ.
func IdempotencyKeyHash(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldIdempotencyKeyHash, v))
}

// RequestFingerprint applies equality check predicate on the "request_fingerprint" field. It's identical to RequestFingerprintEQ.
func RequestFingerprint(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldRequestFingerprint, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldCreatedAt, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldContainsFold(FieldScope, v))
}

// ActorUserIDEQ applies the EQ predicate on the "actor_user_id" field.
func ActorUserIDEQ(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldActorUserID, v))
}

// ActorUserIDNEQ applies the NEQ predicate on the "actor_user_id" field.
func ActorUserIDNEQ(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNEQ(FieldActorUserID, v))
}

// ActorUserIDIn applies the In predicate on the "actor_user_id" field.
func ActorUserIDIn(vs ...int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldIn(FieldActorUserID, vs...))
}

// ActorUserIDNotIn applies the NotIn predicate on the "actor_user_id" field.
func ActorUserIDNotIn(vs ...int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNotIn(FieldActorUserID, vs...))
}

// ActorUserIDGT applies the GT predicate on the "actor_user_id" field.
func ActorUserIDGT(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGT(FieldActorUserID, v))
}

// ActorUserIDGTE applies the GTE predicate on the "actor_user_id" field.
func ActorUserIDGTE(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGTE(FieldActorUserID, v))
}

// ActorUserIDLT applies the LT predicate on the "actor_user_id" field.
func ActorUserIDLT(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLT(FieldActorUserID, v))
}

// ActorUserIDLTE applies the LTE predicate on the "actor_user_id" field.
func ActorUserIDLTE(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLTE(FieldActorUserID, v))
}

// CreatorUserIDEQ applies the EQ predicate on the "creator_user_id" field.
func CreatorUserIDEQ(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldCreatorUserID, v))
}

// CreatorUserIDNEQ applies the NEQ predicate on the "creator_user_id" field.
func CreatorUserIDNEQ(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNEQ(FieldCreatorUserID, v))
}

// CreatorUserIDIn applies the In predicate on the "creator_user_id" field.
func CreatorUserIDIn(vs ...int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldIn(FieldCreatorUserID, vs...))
}

// CreatorUserIDNotIn applies the NotIn predicate on the "creator_user_id" field.
func CreatorUserIDNotIn(vs ...int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNotIn(FieldCreatorUserID, vs...))
}

// CreatorUserIDGT applies the GT predicate on the "creator_user_id" field.
func CreatorUserIDGT(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGT(FieldCreatorUserID, v))
}

// CreatorUserIDGTE applies the GTE predicate on the "creator_user_id" field.
func CreatorUserIDGTE(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGTE(FieldCreatorUserID, v))
}

// CreatorUserIDLT applies the LT predicate on the "creator_user_id" field.
func CreatorUserIDLT(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLT(FieldCreatorUserID, v))
}

// CreatorUserIDLTE applies the LTE predicate on the "creator_user_id" field.
func CreatorUserIDLTE(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLTE(FieldCreatorUserID, v))
}

// APIKeyIDEQ applies the EQ predicate on the "api_key_id" field.
func APIKeyIDEQ(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldAPIKeyID, v))
}

// APIKeyIDNEQ applies the NEQ predicate on the "api_key_id" field.
func APIKeyIDNEQ(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNEQ(FieldAPIKeyID, v))
}

// APIKeyIDIn applies the In predicate on the "api_key_id" field.
func APIKeyIDIn(vs ...int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldIn(FieldAPIKeyID, vs...))
}

// APIKeyIDNotIn applies the NotIn predicate on the "api_key_id" field.
func APIKeyIDNotIn(vs ...int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNotIn(FieldAPIKeyID, vs...))
}

// APIKeyIDGT applies the GT predicate on the "api_key_id" field.
func APIKeyIDGT(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGT(FieldAPIKeyID, v))
}

// APIKeyIDGTE applies the GTE predicate on the "api_key_id" field.
func APIKeyIDGTE(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGTE(FieldAPIKeyID, v))
}

// APIKeyIDLT applies the LT predicate on the "api_key_id" field.
func APIKeyIDLT(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLT(FieldAPIKeyID, v))
}

// APIKeyIDLTE applies the LTE predicate on the "api_key_id" field.
func APIKeyIDLTE(v int64) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLTE(FieldAPIKeyID, v))
}

// APIKeyIDIsNil applies the IsNil predicate on the "api_key_id" field.
func APIKeyIDIsNil() predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldIsNull(FieldAPIKeyID))
}

// APIKeyIDNotNil applies the NotNil predicate on the "api_key_id" field.
func APIKeyIDNotNil() predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNotNull(FieldAPIKeyID))
}

// IdempotencyKeyHashEQ applies the EQ predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashEQ(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashNEQ applies the NEQ predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashNEQ(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNEQ(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashIn applies the In predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashIn(vs ...string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldIn(FieldIdempotencyKeyHash, vs...))
}

// IdempotencyKeyHashNotIn applies the NotIn predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashNotIn(vs ...string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNotIn(FieldIdempotencyKeyHash, vs...))
}

// IdempotencyKeyHashGT applies the GT predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashGT(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGT(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashGTE applies the GTE predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashGTE(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGTE(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashLT applies the LT predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashLT(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLT(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashLTE applies the LTE predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashLTE(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLTE(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashContains applies the Contains predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashContains(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldContains(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashHasPrefix applies the HasPrefix predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashHasPrefix(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldHasPrefix(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashHasSuffix applies the HasSuffix predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashHasSuffix(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldHasSuffix(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashEqualFold applies the EqualFold predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashEqualFold(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEqualFold(FieldIdempotencyKeyHash, v))
}

// IdempotencyKeyHashContainsFold applies the ContainsFold predicate on the "idempotency_key_hash" field.
func IdempotencyKeyHashContainsFold(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldContainsFold(FieldIdempotencyKeyHash, v))
}

// RequestFingerprintEQ applies the EQ predicate on the "request_fingerprint" field.
func RequestFingerprintEQ(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldRequestFingerprint, v))
}

// RequestFingerprintNEQ applies the NEQ predicate on the "request_fingerprint" field.
func RequestFingerprintNEQ(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNEQ(FieldRequestFingerprint, v))
}

// RequestFingerprintIn applies the In predicate on the "request_fingerprint" field.
func RequestFingerprintIn(vs ...string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldIn(FieldRequestFingerprint, vs...))
}

// RequestFingerprintNotIn applies the NotIn predicate on the "request_fingerprint" field.
func RequestFingerprintNotIn(vs ...string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNotIn(FieldRequestFingerprint, vs...))
}

// RequestFingerprintGT applies the GT predicate on the "request_fingerprint" field.
func RequestFingerprintGT(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGT(FieldRequestFingerprint, v))
}

// RequestFingerprintGTE applies the GTE predicate on the "request_fingerprint" field.
func RequestFingerprintGTE(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGTE(FieldRequestFingerprint, v))
}

// RequestFingerprintLT applies the LT predicate on the "request_fingerprint" field.
func RequestFingerprintLT(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLT(FieldRequestFingerprint, v))
}

// RequestFingerprintLTE applies the LTE predicate on the "request_fingerprint" field.
func RequestFingerprintLTE(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLTE(FieldRequestFingerprint, v))
}

// RequestFingerprintContains applies the Contains predicate on the "request_fingerprint" field.
func RequestFingerprintContains(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldContains(FieldRequestFingerprint, v))
}

// RequestFingerprintHasPrefix applies the HasPrefix predicate on the "request_fingerprint" field.
func RequestFingerprintHasPrefix(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldHasPrefix(FieldRequestFingerprint, v))
}

// RequestFingerprintHasSuffix applies the HasSuffix predicate on the "request_fingerprint" field.
func RequestFingerprintHasSuffix(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldHasSuffix(FieldRequestFingerprint, v))
}

// RequestFingerprintEqualFold applies the EqualFold predicate on the "request_fingerprint" field.
func RequestFingerprintEqualFold(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEqualFold(FieldRequestFingerprint, v))
}

// RequestFingerprintContainsFold applies the ContainsFold predicate on the "request_fingerprint" field.
func RequestFingerprintContainsFold(v string) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldContainsFold(FieldRequestFingerprint, v))
}

// ResponseBodyIsNil applies the IsNil predicate on the "response_body" field.
func ResponseBodyIsNil() predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldIsNull(FieldResponseBody))
}

// ResponseBodyNotNil applies the NotNil predicate on the "response_body" field.
func ResponseBodyNotNil() predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNotNull(FieldResponseBody))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.LinkCardOperation) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.LinkCardOperation) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.LinkCardOperation) predicate.LinkCardOperation {
	return predicate.LinkCardOperation(sql.NotPredicates(p))
}
